### ISSUE TITLE
CardComponent Observe never called

### ISSUE THREAD

**Issue by ch4vi** [Adyen/adyen-android#103]
I'm using the CardComponent, I can get the `PaymentMethod` with the correct type SCHEME, I have set the `cardView.observe` but it never gets called. 
As I understand in the documentation section, the observe gets called with every change in the input texts, but it is not happening.
```
private fun startCheckout(paymentMethod: PaymentMethod) {
        val cardConfiguration = CardConfiguration.Builder(
            Locale.getDefault(),
            Environment.TEST,
            resources.displayMetrics,
            PUBLIC_KEY
        ).build()

        val cardComponent = CardComponent.PROVIDER.get(this, paymentMethod, cardConfiguration)
        cardComponent.observe(this, Observer {
            if (it?.isValid == true) {
                // you can now use it.data to send your payments/ request
                Timber.d("OK")
            }else {
                Timber.d("OK")
            }
        })
        cardComponent.observeErrors(this, Observer {
            Timber.e(it.errorMessage)
        })
        cardView.attach(cardComponent, this)
    }
```
There are no error logs or any feedback from the component. I don't know what to do. 
I have other livedata observers and they get called.

**Comment by caiofaustino** [comment]
Hey @ch4vi, currently the `observe` only gets called if the validation of the data changed, so it should get called once you input the whole card data. Can you check if that's the case?

We realize this is probably not the expected behavior and I think it makes more sense to notify like you said for each user input. We will change that probably for the next version.

**Comment by ch4vi** [comment]
Hi!, @caiofaustino that's not happening, I enter a valid card number, valid expiry date and a CVC and nothing happens. Before I get the response from the payment methods request, the view shows a "card holder" editText but after I attach the card component to the view it disappears, probably the library is waiting for the input but this view is not visible.

**Comment by caiofaustino** [comment]
That's weird, we don't see that issue here. Can you share some more information on your implementation so that we can try to reproduce the issue here?

**Comment by ch4vi** [comment]
It's weird, I don't know why it is not calling the observer. An example of a working component would be nice to start with your SDK.
 Another issue that I'm facing is after the v3.1.0, if the view CardView is visible when the activity starts, the app crashes:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.adyen.checkout.card.CardComponent.isStoredPaymentMethod()' on a null object reference
        at com.adyen.checkout.card.CardView$2.onFocusChange(CardView.java:108)
        at android.view.View.onFocusChanged(View.java:6852)
        at android.widget.TextView.onFocusChanged(TextView.java:9720)
        at android.widget.EditText.onFocusChanged(EditText.java:227)
        at android.view.View.handleFocusGainInternal(View.java:6589)
        at android.view.View.requestFocusNoSearch(View.java:9778)
        at android.view.View.requestFocus(View.java:9757)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3066)
        at android.view.ViewGroup.onRequestFocusInDescendants(ViewGroup.java:3110)
        at android.view.ViewGroup.requestFocus(ViewGroup.java:3069)
        at android.view.View.requestFocus(View.java:9724)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2487)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1537)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:959)
        at android.view.Choreographer.doCallbacks(Choreographer.java:734)
        at android.view.Choreographer.doFrame(Choreographer.java:670)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:945)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6776)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)
```
Tested with v3.2.1

Video with the observer not being called:
[aydenPayment.mp4.zip](https://github.com/Adyen/adyen-android/files/3559297/aydenPayment.mp4.zip)

**Comment by caiofaustino** [comment]
You are inputting an AMEX card, the CVC has 4 digits. Try with 7373 and see if the observer gets called please. Still like I said, I understand this behavior is not the expected, so we will work to change that.

Thanks for the stacktrace of the NPE, I'll take a look at that too.

**Comment by ch4vi** [comment]
Still the same with 7373.

**Comment by ch4vi** [comment]
I solved it extending `LifecycleOwner` and just overriding `getLifecycle(): Lifecycle`
