### ISSUE TITLE
Fatal Exception: com.adyen.checkout.core.exception.ComponentException: Stored Blik is not yet supported in this flow.

### ISSUE THREAD

**Issue by michal-chojnacki** [Adyen/adyen-android#1103]
**Describe the bug**
In current version of drop-in app is crashing when I try to pay with saved blik payment method

```
Fatal Exception: com.adyen.checkout.core.exception.ComponentException: Stored Blik is not yet supported in this flow.
       at com.adyen.checkout.dropin.ui.paymentmethods.PaymentMethodListDialogFragment.onStoredPaymentMethodSelected(PaymentMethodListDialogFragment.kt:134)
       at com.adyen.checkout.dropin.ui.paymentmethods.PaymentMethodAdapter.onStoredPaymentMethodClick(PaymentMethodAdapter.kt:228)
       at com.adyen.checkout.dropin.ui.paymentmethods.PaymentMethodAdapter.bindStoredPaymentMethod$lambda-5$lambda-4(PaymentMethodAdapter.kt:122)
       at com.adyen.checkout.dropin.ui.paymentmethods.PaymentMethodAdapter.$r8$lambda$72BzwUPHHO5rlFQ6A1wtgvxi84s()
       at com.adyen.checkout.dropin.ui.paymentmethods.PaymentMethodAdapter$$ExternalSyntheticLambda5.onClick(:4)
       at com.adyen.checkout.components.ui.view.AdyenSwipeToRevealLayout$gestureListener$1.onSingleTapConfirmed(AdyenSwipeToRevealLayout.kt:212)
       at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:329)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7842)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**To Reproduce**
- Make payment with blik and save it as a payment method.
- Try to have second payment. On screen with all payment methods select saved blik method.

**Expected behavior**
App is not crashing and making payment with saved payment blik method is possible

**Comment by OscarSpruit** [comment]
Hi @michal-chojnacki, Blik as a stored payment method is currently not supported. How did you manage to save Blik as a payment method? The drop-in does not support doing this. 

As a quick workaround for now I would suggest to filter out any stored Blik payment methods from the /paymentMethods response.

**Comment by OscarSpruit** [comment]
We will be working on a solution for this. I will update this issue once I know more.

**Comment by michal-chojnacki** [comment]
@OscarSpruit Ok, thank you for the info.

**Comment by OscarSpruit** [comment]
This feature will be shipped with next release! Can't promise an exact date, so I'll notify this issue when it's there.

**Comment by OscarSpruit** [comment]
`4.11.0` just got released, which adds support for stored Blik.
