### ISSUE TITLE
Adyen analytics makes app crash 

### ISSUE THREAD

**Issue by sewerk** [Adyen/adyen-android#1162]
**Describe the bug**
App is crashing through Adyen SDK

**To Reproduce**
Most probably during process recreation of our app (we are using Adyen Drop-in) some internal job is crashing. Problem occurs temporary few times a week
```
android.os.BadParcelableException: Parcelable protocol requires subclassing from Parcelable on class pi.a
    at android.os.Parcel.readParcelableCreator(Parcel.java:3341)
    at android.os.Parcel.readParcelable(Parcel.java:3272)
    at android.os.Parcel.readValue(Parcel.java:3174)
    at android.os.Parcel.readArrayMapInternal(Parcel.java:3567)
    at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
    at android.os.BaseBundle.unparcel(BaseBundle.java:236)
    at android.os.Bundle.getParcelable(Bundle.java:1001)
    at android.content.Intent.getParcelableExtra(Intent.java:8297)
    at com.adyen.checkout.components.analytics.AnalyticsDispatcher.onHandleWork(AnalyticsDispatcher.java:54)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:396)
    at androidx.core.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:387)
    at android.os.AsyncTask$3.call(AsyncTask.java:394)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$4.done(AsyncTask.java:415)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    at java.util.concurrent.FutureTask.run(FutureTask.java:271)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    at java.lang.Thread.run(Thread.java:923)
```

**Expected behavior**
Ui error dialog is shown instead, or nothing at all

**Smartphone (please complete the following information):**
 - Device: Samsung, Motorola and others
 - OS: Android 9 - 13
`com.adyen.checkout:drop-in:4.9.1`

**Comment by jreij** [comment]
Hi, thanks for reaching out, we are investigating this. Do you have any way of reproducing the crash? And do you know if it happens at a specific moment during the drop-in flow or randomly?

**Comment by sewerk** [comment]
From what I know where was an issues in banks yesterday (connected to BLIK), and it occurs more often in such cases. No steps to reproduce unfortunately. 
From our logs it looks like the app process was just started (maybe process recreation). It crashes in the first second of app process creation. It might not be even related to drop-in being opened at that time.
Sorry for no specifics. Let me know if I can help more

**Comment by jreij** [comment]
> It crashes in the first second of app process creation

That's actually very helpful, thanks! I will update you if we figure it out.

**Comment by jreij** [comment]
Another thing that might help is to know which class is making this fail. I can see in the error log:
`Parcelable protocol requires subclassing from Parcelable on class pi.a`
Do you maybe have the Proguard class mappings to check what class is `pi.a`?

**Comment by sewerk** [comment]
```
com.adyen.checkout.components.base.AddressVisibility -> pi.a:
# {"id":"sourceFile","fileName":"AddressVisibility.kt"}
    com.adyen.checkout.components.base.AddressVisibility NONE -> a
    com.adyen.checkout.components.base.AddressVisibility[] $VALUES -> b
    0:65535:void <clinit>():4:4 -> <clinit>
    0:65535:void <init>(java.lang.String,int):3:3 -> <init>
    0:65535:com.adyen.checkout.components.base.AddressVisibility valueOf(java.lang.String):0:0 -> valueOf
    0:65535:com.adyen.checkout.components.base.AddressVisibility[] values():0:0 -> values
```

**Comment by jreij** [comment]
Thanks for the detailed investigation! We should have enough information now to troubleshoot this 👍
