### ISSUE TITLE
Android 27 API Stackoverflow error

### ISSUE THREAD

**Issue by mrdazhuk** [Adyen/adyen-android#124]
...    
 at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
        at com.adyen.threeds2.internal.i.d(Unknown Source:275)
        at com.adyen.threeds2.internal.i.c(Unknown Source:256)
        at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
        at com.adyen.threeds2.internal.i.d(Unknown Source:275)
        at com.adyen.threeds2.internal.i.c(Unknown Source:256)
        at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
        at com.adyen.threeds2.internal.i.d(Unknown Source:275)
        at com.adyen.threeds2.internal.i.c(Unknown Source:256)
        at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
        at com.adyen.threeds2.internal.i.d(Unknown Source:275)
    
    read: unexpected EOF!
STR. 
1. Enter card info(with 3d2s). 
2. Confirmation dialog with code confirmation appears.
3. Enter wrong code and tap Submit. 
4. Tap Cancel after confirmation error

**Comment by caiofaustino** [comment]
Hi, what is your implementation type? (what is your gradle dependency with adyen)
Is this with a live or a test card?

**Comment by mrdazhuk** [comment]
test env, 3.5.0 version(on 3.3.1 was the same), com.adyen.checkout:drop-in, 
the card is from docs: 5454 5454 ...

UPDATES. 
To reproduce this bug enter few times the wrong confirmation code. 

Also I can't pay( DropIn does nothing after entering the correct confirmation code. 
APIs 25 and 28  work correct.

**Comment by caiofaustino** [comment]
I can't seem to reproduce the issue here. Is it 100% reproducible? Can you maybe get the stacktrace or get a video of how to reproduce it.

**Comment by mrdazhuk** [comment]
I can't record a video for now, but it's 100% reproducible. 
Try to enter quickly 123(Submit),1233(Submit), 12345(Submit). I mean enter incorrect codes quickly few times. The stacktrace  is repeatable infinite list of 
at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
at com.adyen.threeds2.internal.i.d(Unknown Source:275)
at com.adyen.threeds2.internal.i.c(Unknown Source:256)

No other info is in logcal.

**Comment by caiofaustino** [comment]
Maybe it's a theming related issue, we try to automatically extend the application Theme, but some things might cause incompatibility.

Can you try to add this line to your `styles.xml` and see if there is any difference?
`<style name="ThreeDS2Theme" parent="Theme.AppCompat.Light"/>`

**Comment by mrdazhuk** [comment]
Looks like your answer should be here
https://github.com/Adyen/adyen-android/issues/125.

Anyway, I've tried. **ThreeDS2Theme** isn't related to button's style. The reason is using the same compat-style with `Button` and `CompatButton` Button doesn't rely on Compat-styles.
