### ISSUE TITLE
3DS2 payments (ex. Revolut) fails

### ISSUE THREAD

**Issue by tugal-dev** [Adyen/adyen-android#128]
We have na implementation in Android using Adyen SDK , to get Credit cards payments. Right now we are observing that at least payments with Revolut  cards are failing with the following error  
 
java.lang.IllegalStateException: Must not be called on the main application thread
at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:51)
at com.google.android.gms.common.internal.Preconditions.checkNotMainThread(Unknown Source:48)
at com.google.android.gms.tasks.Tasks.await(Unknown Source:24)
at com.adyen.threeds2.internal.c.a.c.f$b.a(Unknown Source:151)
at com.adyen.threeds2.internal.c.a.c.f.a(Unknown Source:59)
at com.adyen.threeds2.internal.c.a.c.f$d.c(Unknown Source:104)
at com.adyen.threeds2.internal.c.a.c.f$d.b(Unknown Source:91)
at com.adyen.threeds2.internal.c.a.d.a(Unknown Source:39)
at com.adyen.threeds2.internal.c.b.a(Unknown Source:87)
at com.adyen.threeds2.internal.c.b.<init>(Unknown Source:54)
at com.adyen.threeds2.internal.c.b.a(Unknown Source:46)
at com.adyen.threeds2.internal.g.initialize(Unknown Source:93)
at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:107)
at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:82)
at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
at android.os.Handler.handleCallback(Handler.java:873)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7032)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

On other posts we checked that a way o solve this issue would be to upgarde the SDK to version 2.4.8.

Our uqestion is is we can upgrade the SDK to version 2.4.8 mantaining the APIs on the server in version 37.

We have a roadmap for upgrade , but right now we would like to solve this issues asap.

Thanks

**Comment by ArmanSo** [comment]
Hi @tugal-dev 
as I checked, there was an issue in 3DS2 library that time and we released version `2.4.8` for that and unfortunately there is no way to fix that issue without updating to version `2.4.8`


Bests,
Arman.

**Comment by tugal-dev** [comment]
Hi @ArmanSo 

Thanks for the reply. 
We would like to know if we can use the SDK version 2.4.8 and keep using API version 37.

Thanks

Kind regards

**Comment by tugal-dev** [comment]
Hi @ArmanSo 

We are using the following end points : 

PaymentSession and PaymentResults.

Can you please help us ?

Thanks

**Comment by ArmanSo** [comment]
Hi @tugal-dev sorry for late replay.

It should be fine with version 37

What is the issue with `PaymentSession` and `PaymentResults` end points?

**Comment by tugal-dev** [comment]
Hi @ArmanSo 

thanks for the help. There is no issue, it is just the endpoints that we are using .

Thanks for the feedback
