### ISSUE TITLE
Drop-in in java?

### ISSUE THREAD

**Issue by Wlf46** [Adyen/adyen-android#139]
Does exist a drop-in documentation/example in java?
Thank you!

**Comment by caiofaustino** [comment]
Hey there,

Unfortunately no, we chose to put the examples in Kotlin to make them more up to date. But we don't use any Kotlin specific language feature, the sintax should be pretty similar.

Do you have any specific questions about any of the examples?

**Comment by Wlf46** [comment]
I have made a post  /paymentMethods request to my server and I obtanin a JSONObject with PaymentMethodsApiResponse.

PaymentMethodsApiResponse paymentMethodsApiResponse = PaymentMethodsApiResponse.SERIALIZER.deserialize(jsonObject);

Than I start DropIn with this code:

CardConfiguration cardConfiguration = new CardConfiguration.Builder(MyActivity.this, strRandom).build();
DropInConfiguration dropInConfiguration = new DropInConfiguration.Builder(MyActivity.this, AdyenDropInService.class).setEnvironment(Environment.TEST).addCardConfiguration(cardConfiguration).build();
DropIn.startPayment(MyActivity.this, paymentMethodsApiResponse, dropInConfiguration);

But the DropIn don't start; I don't understand what's the problem!

**Comment by caiofaustino** [comment]
Can you try taking a look at the logcat to see if there are any errors? I think you probably have an invalid PublicKey in your `strRandom` but the logs should give you a better idea.

**Comment by Wlf46** [comment]
In logcat I don't see errors.
PublicKey what does it must contain?

**Comment by caiofaustino** [comment]
You can find the PublicKey of your account in the Customer Area, I don't have access to that but you can contact Support, they can help you with that.

You don't see any error and the Drop-in doesn't start? Are you in a Debug build? Maybe to confirm you can add this code to force the logging. But make sure to not do this in the production app.
`Logger.setLogcatLevel(Log.DEBUG);`

**Comment by Wlf46** [comment]
The problem was the PublicKey. ;)

Thank you, now it start but I have a crash when I push Pay button!

11-27 15:53:15.566 3301-3301/com.test.testapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.testapp, PID: 3301
    java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 
     Caused by: org.json.JSONException: Value action of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:111)
        at org.json.JSONObject.<init>(JSONObject.java:160)
        at org.json.JSONObject.<init>(JSONObject.java:173)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:277)
        at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:106)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195) 

What is the value string passed as JSONObject?

**Comment by caiofaustino** [comment]
Ok so the DropInService you implemented should return a `CallResult`.

If the server response has an Action to be handled you pass the JSON of the Action object as a string in the CallResult. Something like this:
`new CallResult(CallResult.ResultType.ACTION, paymentsResponse.get("action").toString())`
If there is no Action you can just return Finished and some String for you to receive back when the Drop-in finishes, something like:
`new CallResult(CallResult.ResultType.FINISHED, "Payment sucessfull")`
or
`new CallResult(CallResult.ResultType.FINISHED, "REFUSED")`

**Comment by Wlf46** [comment]
Without a DropInService in Java I'm not able to implement a call to my server. :(
Could you kindly post me a DropInService in Java? Thank you

**Comment by caiofaustino** [comment]
We have a simplified version of the DropInService that will handle the CallResult stuff for you, maybe it's easier for you to use. 

The draw back is that you should make sure not to pass sensitive data like risk assessment data from the Adyen response to your server back into the app, so your server should remove that part of the response before sending to the app for security.

It goes something like this:
```java
public class YourDropInService extends SimplifiedDropInService {

    @Nullable
    @Override
    public JSONObject makePaymentsCallOrFail(@NotNull JSONObject jsonObject) {
        JSONObject serverResponse = null;
        try {
            // send jsonObject to your server using your preferred connection method like Moshi for example
            // server should fill the rest of the data and call /payments endpoint.
            serverResponse = sendDataToServerforPayments(jsonObject);
            // your server should return the filtered response from Adyen
        } catch (IOException e) {
            // can just return null
        }
        return serverResponse;
    }
    
    @Nullable
    @Override
    public JSONObject makeDetailsCallOrFail(@NotNull JSONObject jsonObject) {
        JSONObject serverResponse = null;
        try {
            // same as the above but for /payments/details endpoint instead
            serverResponse = sendDataToServerforDetails(jsonObject);
            // your server should return the filtered response from Adyen
        } catch (IOException e) {
            // can just return null
        }
        return serverResponse;
    }
}
```

**Comment by Wlf46** [comment]
My backoffice server return me a response with a JSON like this:
{"pspReference":"853575293444731D","resultCode":"Authorised","merchantReference":"1"}
I return this response to DropInServce Callresult:
String response = JSONResponse.toString(); 
return new CallResult(CallResult.ResultType.ACTION, response);

The APP give me a crash:
12-02 14:39:57.549 12468-12468/com.test.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.myapp, PID: 12468
    com.adyen.checkout.core.exception.CheckoutException: Action type not found
        at com.adyen.checkout.base.model.payments.response.Action$1.deserialize(Action.java:52)
        at com.adyen.checkout.base.model.payments.response.Action$1.deserialize(Action.java:33)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:277)
        at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:106)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5951)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

The response that I return to Callresult is correct?

**Comment by Wlf46** [comment]
If I return ResultType.FINISHED and resultCode "Authorised" that return me from your payment server the App give me ActivityNotFoundException: No Activity found to handle Intent 

android.content.ActivityNotFoundException: No Activity found to handle Intent { (has extras) }
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1499)
        at android.app.Activity.startActivityForResult(Activity.java:3942)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:676)
        at android.app.Activity.startActivityForResult(Activity.java:3889)
        at androidx.fragment.app.FragmentActivity.startActivityForResult(FragmentActivity.java:663)
        at android.app.Activity.startActivity(Activity.java:4213)
        at android.app.Activity.startActivity(Activity.java:4181)
        at com.adyen.checkout.dropin.ui.DropInActivity.sendResult(DropInActivity.kt:293)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:274)
        at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:106)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:5953)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

**Comment by caiofaustino** [comment]
There is no Action in that response, the result `Authorised` means the payment was sucessfull.
You can just return `new CallResult(CallResult.ResultType.FINISHED, "Authorised");` for example.

**Comment by SMJ93** [comment]
@Wlf46 Did you mange to get this working in Java?

I'm trying to create a react-native bridge and hitting a lot of brick walls 😕

**Comment by wilochoa** [comment]
@Wlf46 did you implement the drop-in in java? could you help me? with an example? or something?

**Comment by Wlf46** [comment]
You don't need to implement tre drop-in in java; you can extend your Drop-in service and write it in Java.
