### ISSUE TITLE
Crash: Calling startActivity() from outside of an Activity

### ISSUE THREAD

**Issue by georgij** [Adyen/adyen-android#15]
It crashes on Android 5 & 6 with:

`android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?`

java.lang.IllegalStateException: Could not execute method of the activity

at android.view.View$1.onClick(View.java:4020)
at android.view.View.performClick(View.java:4780)
at android.view.View$PerformClick.run(View.java:19866)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5254)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at android.view.View$1.onClick(View.java:4015)
at android.view.View.performClick(View.java:4780) 
at android.view.View$PerformClick.run(View.java:19866) 
at android.os.Handler.handleCallback(Handler.java:739) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5254) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) Caused by: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
at android.app.ContextImpl.startActivity(ContextImpl.java:1238)
at android.app.ContextImpl.startActivity(ContextImpl.java:1225)
at android.content.ContextWrapper.startActivity(ContextWrapper.java:323)
at com.adyen.ui.DefaultPaymentRequestListener.onPaymentDataRequested(DefaultPaymentRequestListener.java:34)
at com.adyen.core.PaymentStateHandler.requestPaymentData(PaymentStateHandler.java:190)
at com.adyen.core.PaymentStateHandler.onStateChanged(PaymentStateHandler.java:120)
at com.adyen.core.internals.PaymentProcessorStateMachine.onStateChanged(PaymentProcessorStateMachine.java:26)
at com.adyen.core.internals.PaymentProcessorStateMachine.onTrigger(PaymentProcessorStateMachine.java:39)
at com.adyen.core.PaymentRequest.start(PaymentRequest.java:60)

**Comment by georgij** [comment]
Found the reason. I should use `this` instead of `getApplicationContext()`.
