### ISSUE TITLE
makeDetailsCall is never called

### ISSUE THREAD

**Issue by lalesan** [Adyen/adyen-android#150]
Good morning. I'm trying to integrate android sdk in out project. We are able to call makePaymentsCall but makeDetailsCall is never called. After click pay button inside adyen view, we get this error in logs:

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:503)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: org.json.JSONException: Value action of type java.lang.String cannot be converted to JSONObject
        at org.json.JSON.typeMismatch(JSON.java:112)
        at org.json.JSONObject.<init>(JSONObject.java:163)
        at org.json.JSONObject.<init>(JSONObject.java:176)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:277)
        at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:106)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
```

And this is our DropInService implementation:

```
public class SPDropInService extends DropInService {
    @NotNull
    @Override
    public CallResult makeDetailsCall(@NotNull JSONObject jsonObject) {
        TLog.d("makeDetailsCall: "+jsonObject.toString());
        return new CallResult(CallResult.ResultType.FINISHED, "Payment sucessfull");
    }

    @NotNull
    @Override
    public CallResult makePaymentsCall(@NotNull JSONObject jsonObject) {
        TLog.d("makePaymentsCall: "+jsonObject.toString());
        return new CallResult(CallResult.ResultType.ACTION, "action JSON object");
    }
}
```

Thank you

**Comment by caiofaustino** [comment]
Hi @lalesan,

So the content of the `CallResult` in case of an action needs to be a string that represents the JSON of the action result that came from the /payments response.

For example:
```
{
  "method": "GET",
  "paymentData": "<data_blob>",
  "paymentMethodType": "ideal",
  "type": "redirect",
  "url": "https://some.url"
}
```
So the 2nd parameter of the CallResult should be a string with that object.
