### ISSUE TITLE
Drop-In:3.5.0: Fragment already added(LOADING_DIALOG_FRAGMENT)

### ISSUE THREAD

**Issue by mrdazhuk** [Adyen/adyen-android#154]
Hi. I've received a crash in Crashlitycs. 
Samsung Galaxy S6 - Android 7
Probably this bug was fixed after, but I made a decision to notify it. 
  
Fatal Exception: java.lang.IllegalStateException: Fragment already added: ıս{e3d3a3e (97a5406c-c577-4dab-b3de-0da2483fcd87) LOADING_DIALOG_FRAGMENT}
       at androidx.fragment.app.FragmentManagerImpl.addFragment(FragmentManagerImpl.java:1379)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:399)
       at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2076)
       at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1866)

**Comment by caiofaustino** [comment]
Hi there,

Yes indeed this should be fixed from version 3.5.1 onwards. Feel free to reopen the issue if you still see problems after updating.

Regards
