### ISSUE TITLE
Drop-In:3.6.1: Unable to start activity

### ISSUE THREAD

**Issue by JoeCiou** [Adyen/adyen-android#158]
Hi, I got a crash in Samsung Galaxy S9 / Android 8.

stack trace:
```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.buynship.BuyandshipApp/com.adyen.checkout.dropin.ui.DropInActivity}: g.a.a.d.b.a: ModelObject protocol requires a ModelObject.Serializer object called SERIALIZER on class a
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2955)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
```
Caused by g.a.a.d.b.a: ModelObject protocol requires a ModelObject.Serializer object called SERIALIZER on class a
       at g.a.a.d.d.c.a(:56)
       at g.a.a.d.d.c.a()
       at g.a.a.d.d.b$a.createFromParcel(:8)
       at g.a.a.d.d.b$a.createFromParcel()
       at android.os.Parcel.readParcelable(Parcel.java:2797)
       at android.os.Parcel.readValue(Parcel.java:2691)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3058)
       at android.os.BaseBundle.unparcel(BaseBundle.java:257)
       at android.os.Bundle.getParcelable(Bundle.java:888)
       at android.content.Intent.getParcelableExtra(Intent.java:7734)
       at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(:89)
       at android.app.Activity.performCreate(Activity.java:7174)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```
```
Caused by java.lang.NoSuchFieldException: SERIALIZER
       at java.lang.Class.getField(Class.java:1601)
       at g.a.a.d.d.c.a(:2)
       at g.a.a.d.d.c.a()
       at g.a.a.d.d.b$a.createFromParcel(:8)
       at g.a.a.d.d.b$a.createFromParcel()
       at android.os.Parcel.readParcelable(Parcel.java:2797)
       at android.os.Parcel.readValue(Parcel.java:2691)
       at android.os.Parcel.readArrayMapInternal(Parcel.java:3058)
       at android.os.BaseBundle.unparcel(BaseBundle.java:257)
       at android.os.Bundle.getParcelable(Bundle.java:888)
       at android.content.Intent.getParcelableExtra(Intent.java:7734)
       at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(:89)
       at android.app.Activity.performCreate(Activity.java:7174)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
       at android.app.ActivityThread.-wrap11()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
       at android.os.Handler.dispatchMessage(Handler.java:105)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6938)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

Let me know if you need more information.

**Comment by ArmanSo** [comment]
Hi @JoeCiou 

Can you please provide DropInConfiguration that you're using? 

Thanks.

**Comment by caiofaustino** [comment]
This looks like a Proguard issue. Did you add the Progurard rules we suggest on the Readme page?
```
-keep class com.adyen.checkout.base.model.** { *; }
-keep class com.adyen.threeds2.** { *; }
-keepclassmembers public class * implements com.adyen.checkout.base.PaymentComponent {
   public <init>(...);
}
```

**Comment by JoeCiou** [comment]
Yes, it is a Proguard issue, I fixed it when I add your suggested code.
Thank you very much!
