### ISSUE TITLE
ClassNotFoundException: Cash App Pay

### ISSUE THREAD

**Issue by christianfindsen** [Adyen/adyen-android#1627]
**Describe the bug**
We have just implemented Cash App Pay and upon release we are seeing ClassNotFoundException for some internal CashAppPay.
All crashing users are on Android 10
We are running Adyen SDK `5.2.0`
Checkout Components

**To Reproduce**
Can't reproduce it myself and doesn't affect all users nor is it all Android 10 users

**Expected behavior**
Not crashing ;) 

**Smartphone (please complete the following information):**
 - Device: Several models, Samsung S9, J6, S10, ect ect
 - OS: [Android 10]

**Additional context**
StackTrace looks like this:
Fatal Exception: java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: java.lang.ClassNotFoundException: app.cash.paykit.core.CashAppPayInitializer
       at android.app.ActivityThread.installProvider(ActivityThread.java:7769)
       at android.app.ActivityThread.installContentProviders(ActivityThread.java:7309)
       at android.app.ActivityThread.handleMakeApplication(ActivityThread.java:7166)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7134)
       at android.app.ActivityThread.access$1600(ActivityThread.java:274)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2102)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by ozgur00** [comment]
Hi @christianfindsen! Thanks for bringing the issue into our attention. Before we start investigating it can you check the SDK version you're using and share it again, I believe there's a typo or a mixup since we don't have `5.12` version available on Android.

**Comment by christianfindsen** [comment]
Hi @ozgur00. Yes there was a type in there. We are on `5.2.0`

**Comment by ozgur00** [comment]
Hi again @christianfindsen. I am not able to reproduce the crash on my end either. After discussing internally we decided to contact Cash App team about the issue. And in order to investigate the issue we'd appreciate as much information as possible. Is this happening only on production, or does it also happen on the debug builds? In the builds that this crash is happening, is proguard/r8/minify enabled?

**Comment by christianfindsen** [comment]
We didn't find it during our testing phase nor with debug builds, we only saw it after releasing it to production.
Yes, R8 is enabled on the Prod version.

**Comment by ozgur00** [comment]
Hi @christianfindsen! We have reached out to our contacts at Cash App about the issue and they have mentioned they were aware of it and resolved the issue. It was correlated to a backend upgrade and since that is resolved they do not expect more occurrences of this issue. Let us know if you see any more instances of this issue.

**Comment by christianfindsen** [comment]
Thanks for the update @ozgur00. We have also not seen any more crashes lately.
