### ISSUE TITLE
Can't redirect to Pix Payment App on Checkout.

### ISSUE THREAD

**Issue by AmitavSingh** [Adyen/adyen-android#1645]
**Describe the bug**
In case of Pix payment the Adyen QR Component doesn't redirect to payment screen/ Pix app. 
The QRCode Component cannot handle the QR Code Action, when of Pix Payment method is selected.

**To Reproduce**
1. Go to Checkout and Select the Pix Payment option.
2. Click on Pay and pass the QRCodeAction to the QRCodeComponent.
3. The user remains on the same screen and there is no redirection to Pix App.

**Expected behavior**
After user selects Pix payment option, the QRCodeAction should be processed by the QRCodeComponent and user should be redirected to Pix App to complete the payment. 

**Screenshots**
![image](https://github.com/Adyen/adyen-android/assets/51942745/65e0b864-cab9-46bd-a116-4d4abe03e05a)

**Desktop (please complete the following information):**
 - OS: Android
 - Version - v13
 - Adyen QRCode Component Version: v4.13.4

**Smartphone (please complete the following information):**
 - Device: Pixel 4
 - OS: Android
 - Version: 13

**Additional context**
In the screenshot, the last step of handleActionInternal the check !PROVDER.requireView(action) returns false and hence we couldn’t call the redirectDelegate.makeRedirect().

**Comment by araratthehero** [comment]
Hi @AmitavSingh, thanks for reaching out.

The PIX integration does not redirect users to any app, as [our documentation](https://docs.adyen.com/payment-methods/pix/android-component/) explains:

> When a shopper is ready to pay with Pix on your Android app:
> 1. The shopper chooses to pay with Pix on your Android app.
> 2. Your Android app shows a QR code or QR code data for the shopper to copy.
> 3. The shopper opens their banking or wallet app participating in Pix.
> 4. The shopper selects Pix, scans the QR code or pastes QR code data, and then confirms the payment.

What I suggest is:
- Follow our documentation [here](https://docs.adyen.com/payment-methods/pix/android-component/).
- Verify if you see the screen with a "Copy code" button.
- Test the integration as explained in the documentation.

After verifying these steps, let us know if you have any further questions.

**Comment by AmitavSingh** [comment]
Hi @araratthehero I have tried to make the payment via Pix but I didn't see the Screen with Copy Code button.
The user is still in the same payment page and nothing happens after he select Pix.

**Comment by AmitavSingh** [comment]
In my attachment we can see that we are passing a valid QRCodeAction to the Adyen Component.

**Comment by araratthehero** [comment]
Hi @AmitavSingh, to assist you further, could you please send:
- A screen recording of the flow
- The part of code where you configure the component
- The part of code where you pass the action to the component
- Extensive logs, which you can enable by calling `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)` in your application class and filter your logs by `CO.` to see the checkout logs only.
- Any additional information/code you think can assist further

**Comment by AmitavSingh** [comment]
Hi @araratthehero  Please find below deatils

Code Snippet-
<img width="1276" alt="image" src="https://github.com/Adyen/adyen-android/assets/51942745/8555d964-cd72-40b5-9ef4-f80c11cf8498">

Logcat -
<img width="1458" alt="image" src="https://github.com/Adyen/adyen-android/assets/51942745/9f0a8ba6-2edc-428e-a0d7-a6ae19cc0c93">

Screen Recording-
Description : user Selects Pix payment, we pass QRCodeAction to Adyen, but nothing happens.

https://github.com/Adyen/adyen-android/assets/51942745/04ef2ed7-89cd-48c8-8d0d-65a02482edc1

**Comment by araratthehero** [comment]
Hi @AmitavSingh, please enable extensive logs by calling setLogcatLevel(Log.VERBOSE) in your application class. Then filter the logs by CO. and send everything from the logcat here.

**Comment by araratthehero** [comment]
@AmitavSingh, the first screenshot you shared shows the correct behavior: PIX does not support redirect, so it displays a view, which can be a QR code or a code for the user to copy. To make it visible, you need to show the `QRCodeView`, which should be attached to the `QRCodeComponent`. You can find the guide [here](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=4.13.4#set-up-components).

Other payment methods likely worked because they perform a redirect, so you didn't need to ensure the view was visible.

Could you check if you are displaying the `QRCodeComponent` correctly?

**Comment by AmitavSingh** [comment]
Hi @araratthehero 

Here is the error logs

2024-05-31 16:20:18.458  D  mStatusPollingRunnable.run()
2024-05-31 16:20:18.458  V  getStatus
2024-05-31 16:20:18.458  V  call - https://checkoutshopper-test.adyen.com/checkoutshopper/services/PaymentInitiation/v1/status?token=test_VN3KFAZIGVGX3G452X6VAVDAEEEN23YS
2024-05-31 16:20:18.564  V  done
2024-05-31 16:20:18.565  E  Execution failed.
                            java.util.concurrent.ExecutionException: java.io.IOException: <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1></body></html>
                            	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
                            	at java.util.concurrent.FutureTask.get(FutureTask.java:205)
                            	at com.adyen.checkout.components.status.api.StatusConnectionTask.done(StatusConnectionTask.java:55)
                            	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
                            	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
                            	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
                            	at com.adyen.checkout.core.api.ConnectionTask.run(ConnectionTask.java:67)
                            	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
                            	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                            	at java.lang.Thread.run(Thread.java:1012)
                            Caused by: java.io.IOException: <!doctype html><html lang="en"><head><title>HTTP Status 403 – Forbidden</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 403 – Forbidden</h1></body></html>
                            	at com.adyen.checkout.core.api.Connection.parseException(Connection.java:134)
                            	at com.adyen.checkout.core.api.Connection.handleResponse(Connection.java:175)
                            	at com.adyen.checkout.core.api.Connection.post(Connection.java:118)
                            	at com.adyen.checkout.components.status.api.StatusConnection.call(StatusConnection.java:39)
                            	at com.adyen.checkout.components.status.api.StatusConnection.call(StatusConnection.java:25)
                            	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                            	at com.adyen.checkout.core.api.ConnectionTask.run(ConnectionTask.java:67) 
                            	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463) 
                            	at java.util.concurrent.FutureTask.run(FutureTask.java:264) 
                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                            	at java.lang.Thread.run(Thread.java:1012) 
2024-05-31 16:20:18.573  E  onFailed
2024-05-31 16:20:18.594  W  presentDisplay display has no layers to compose, flushing client target buffer.

**Comment by AmitavSingh** [comment]
Hi @araratthehero I have done the initialisation of AdyenQRCodeComponent as below

    **fun initQRCodeAdyenComponent(activity: FragmentActivity): QRCodeComponent {
        val configuration = QRCodeConfiguration.Builder(activity, clientKey)
            .setEnvironment(if (isRelease()) Environment.LIVE else Environment.TEST)
            .build()
        return QRCodeComponent.PROVIDER.get(activity, activity.application, configuration)
    }**

And I am passing the QRCodeAction to handleAction method of the Component

**QrCodeAction.SERIALIZER.deserialize(JSONObject(action.original.orEmpty())).let { decodedAction ->
                          adyenQRCodeComponent?.handleAction(requireActivity(), decodedAction) ?: throw CheckoutProcessException.AdyenError("Adyen QRCode component is not initialized.")
                        }**

Can you please tell me how do I initalize the QRCodeView together with QRCodeAdyenComponent, as you have said above?

**Comment by araratthehero** [comment]
Hi @AmitavSingh, as I mentioned above, you can find it in [the guide](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=4.13.4#set-up-components).

The following is copied from [here](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=4.13.4#set-up-components:~:text=Add%20the%20Component%20view%20to%20your%20layout.%20You%20will%20attach%20the%20initialized%20component%20to%20this%20view%20in%20Step%203.) and shows how to add a component view to your layout.

> Step 1: Set up Components
> ...
> 2. Add the Component view to your layout. You will attach the initialized component to this view in Step 3.
> ```
> 
> 
> <com.adyen.checkout.card.CardView
>      android:id="@+id/YOUR_COMPONENT_VIEW_ID"
>      .../>
> ```
**Note: Replace `CardView` with `QRCodeView`.**

As stated in the snippet above, in [Step 3](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=4.13.4#collect-payment-details) you will attach the initialized component to the view you created:

> Step 3: Collect payment details
> In this step, we use the client-side Component to collect payment details from your shopper.
> ...
> 4. Attach the Component to the view to start getting your shopper's payment details. You need to call attach from the payment method's Component view and pass in two things:
> - the component object (for example, cardComponent)
> - the context (for example, this@YourActivity)
> ```
> // Replace CardComponent with the payment method Component that you want to add.
> // See list of supported payment methods at https://docs.adyen.com/online-payments/supported-payment-methods
> cardView.attach(cardComponent, this@YourActivity)
> ```
> ...

Attaching a component to a view is as simple as calling `cardView.attach(cardComponent, this@YourActivity)` on your view.

I recommend reading [the guide](https://docs.adyen.com/online-payments/build-your-integration/advanced-flow/?platform=Android&integration=Components&version=4.13.4) thoroughly and following the steps to understand how the components work, manage data flow correctly, and set it up optimally for your project.

**Comment by AmitavSingh** [comment]
Hi @araratthehero Thanks for your help. Its working now.
