### ISSUE TITLE
Drop-in 3.6.2 crashes when used with Material library 1.1.0

### ISSUE THREAD

**Issue by geertjan-tiqets** [Adyen/adyen-android#166]
I just updated from `com.google.android.material:material:1.0.0` to version 1.1.0, and now the Adyen SDK (3.6.2) is crashing whenever I select to pay with credit card, with the message:

> java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

(I've downgraded to material 1.0.0 for now, but that version has a [bug](https://stackoverflow.com/questions/51891415/nullpointerexception-on-meizu-devices-in-editor-updatecursorpositionmz) causing crashes in our app, so we'd like to update to 1.1.0 as soon as possible.)

Full strack trace of the crash:

```2020-02-07 10:51:53.475 11863-11863/com.tiqets.tiqetsapp.development E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tiqets.tiqetsapp.development, PID: 11863
    android.view.InflateException: Binary XML file line #9 in com.tiqets.tiqetsapp.development:layout/fragment_card_component: Binary XML file line #9 in com.tiqets.tiqetsapp.development:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.DropInCardView
    Caused by: android.view.InflateException: Binary XML file line #9 in com.tiqets.tiqetsapp.development:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.DropInCardView
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #65 in com.tiqets.tiqetsapp.development:layout/view_card_component_dropin: Binary XML file line #65 in com.tiqets.tiqetsapp.development:layout/view_card_component_dropin: Error inflating class com.adyen.checkout.card.CardView
     Caused by: android.view.InflateException: Binary XML file line #65 in com.tiqets.tiqetsapp.development:layout/view_card_component_dropin: Error inflating class com.adyen.checkout.card.CardView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.card.DropInCardView.<init>(DropInCardView.kt:33)
2020-02-07 10:51:53.476 11863-11863/com.tiqets.tiqetsapp.development E/AndroidRuntime:     at com.adyen.checkout.card.DropInCardView.<init>(DropInCardView.kt:29)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: android.view.InflateException: Binary XML file line #21 in com.tiqets.tiqetsapp.development:layout/card_view: Binary XML file line #21 in com.tiqets.tiqetsapp.development:layout/card_view: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #21 in com.tiqets.tiqetsapp.development:layout/card_view: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.card.CardView.<init>(CardView.java:77)
        at com.adyen.checkout.card.CardView.<init>(CardView.java:67)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1123)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1084)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1126)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:656)
2020-02-07 10:51:53.476 11863-11863/com.tiqets.tiqetsapp.development E/AndroidRuntime:     at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.card.DropInCardView.<init>(DropInCardView.kt:33)
        at com.adyen.checkout.card.DropInCardView.<init>(DropInCardView.kt:29)
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:854)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:36)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
        at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
        at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:248)
        at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:222)
        at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:150)
        at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:120)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:424)
        at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:396)
        	... 51 more```

**Comment by caiofaustino** [comment]
`Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).`

This is a Theming issue, the components try to use your `AppTheme` by default to inherit the customizations. But if you use a different theme name, or if you want to make additional customizations you can simply override the themes to whats suits your needs.

```
<!-- Placeholder to be overridden by main app -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight" />

    <!-- Base theme for Checkout -->
    <style name="AdyenCheckout" parent="AppTheme" />
```

You can fix this crash like this by changing your AppTheme parent or overriding the Checkout theme to set a new parent.

```
<!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.MaterialComponents.DayNight">
```
OR
```
<style name="AdyenCheckout" parent="Theme.MaterialComponents.DayNight" />
```

**Comment by geertjan-tiqets** [comment]
Thanks, using a `Theme.MaterialComponents` theme indeed solves the crash.

But now I am noticing a color glitch in the Adyen credit card screen, which only occurs with Material library 1.1.0.

Using Material 1.0.0:
![adyen1](https://user-images.githubusercontent.com/53077876/74033444-72602300-49b6-11ea-9e6a-1285e64b1398.png)

Using Material 1.1.0:
![adyen2](https://user-images.githubusercontent.com/53077876/74033459-77bd6d80-49b6-11ea-944f-b4169b702030.png)

(In Material 1.0.0 `Theme.MaterialComponents.DayNight` is not available, but I'm getting the same result with `Theme.MaterialComponents.Light.DarkActionBar` using both 1.0.0 and 1.1.0.)

**Comment by caiofaustino** [comment]
Yeah I noticed that too, it's probably that the color for that text is set from a different place in the Material components Theme than it was on the AppCompat Themes. Or that the primaryColor is not being taken correctly.

I'd suggest you make some tests around that styling and override our styles to match your needs.
This is where we set those configurations. 
https://github.com/Adyen/adyen-android/blob/master/base-ui/src/main/res/values/styles.xml#L35

I'd appreciate if you share with us how you solved the issue to see if we can make that backward compatible as well.

Hope this helps :)

**Comment by geertjan-tiqets** [comment]
Ok, I solved it by copying `AdyenCheckout.TextInputLayout` into our own styles file, and adding `hintTextColor`:

    <style name="AdyenCheckout.TextInputLayout" parent="Widget.MaterialComponents.TextInputLayout.OutlinedBox">
        <item name="boxStrokeColor">@color/primaryColor</item>
        <item name="hintTextAppearance">@style/AdyenCheckout.HintTextStyle</item>
        <item name="hintTextColor">@color/primaryColor</item>
        <item name="android:minHeight">@dimen/input_layout_height</item>
    </style>

**Comment by caiofaustino** [comment]
Nice! I'll make some tests and see if I can add the property to our base layout for the next release.

**Comment by geertjan-tiqets** [comment]
Hi, just wanted to let you know that the input field color glitch is still happening in version 3.6.6.

**Comment by caiofaustino** [comment]
Yes, thanks for the reminder, we are tracking and will look into this issue in the future. Thank you for the patience.
