### ISSUE TITLE
IllegalCharsetNameException on production

### ISSUE THREAD

**Issue by Nonda95** [Adyen/adyen-android#1688]
**Describe the bug**
We received a crash report on production, here's the stack trace:
```
Caused by java.nio.charset.IllegalCharsetNameException: TUG,9
       at java.nio.charset.Charset.checkName(Charset.java:314)
       at java.nio.charset.Charset.lookup2(Charset.java:516)
       at java.nio.charset.Charset.lookup(Charset.java:494)
       at java.nio.charset.Charset.forName(Charset.java:560)
       at com.adyen.threeds2.internal.Charsets.<clinit>(:31)
       at com.adyen.threeds2.internal.util.Base64.<clinit>(:36)
       at com.adyen.threeds2.internal.util.StringObfuscator.obfuscate(:30)
       at com.adyen.threeds2.internal.SdkIdentifier.CipherOutputStream(:49)
       at com.adyen.threeds2.internal.SdkIdentifier.refreshSdkAppId(:45)
       at com.adyen.threeds2.internal.AppUpgradeBroadcastReceiver.onReceive(:33)
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:4894)
       at android.app.ActivityThread.-$$Nest$mhandleReceiver()
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2420)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8757)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**To Reproduce**
I wasn't able to reproduce it on the test environment

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy A13
 - OS: Android 13
 - SDK Version 5.4.0

**Comment by tkuntubayev** [comment]
Hi @Nonda95 
Thank you for the report! We'll review this soon and keep you updated once we find the cause

**Comment by tkuntubayev** [comment]
Hi @Nonda95,

We wanted to check in and ask if you're still experiencing this issue. If so, could you please let us know which version of the SDK you are currently using and how often the issue happens? Additionally more details like device, OS, app build info, or any other observed patterns would greatly help.

Since the time this issue was opened, we haven't seen any other similar reports, and we've also not been able to reproduce the behavior on our side.

If you're still encountering the issue, we'd be happy to investigate further with more details.

Looking forward to your update!
