### ISSUE TITLE
Problem with Android SDK integration

### ISSUE THREAD

**Issue by m-glebova** [Adyen/adyen-android#17]
Hi guys, I have a problem running your example on Android (checkoutdemo), I cloned the latest version. The log is attached below. My API configuration looks like this:
SERVER_URL: https://checkout-test.adyen.com/services/PaymentSetupAndVerification/v31/
API_HEADER_KEY: X-API-Key
API_KEY: Checkout API Key from the Web Service User (for some strange reason Checkout Demo Server API Key does not work for me)
<pre>com.adyen.checkoutdemo E/PaymentBroadcastReceivers: Provided payment data response is invalid
                                                                                 org.json.JSONException: No value for publicKeyToken
                                                                                     at org.json.JSONObject.get(JSONObject.java:392)
                                                                                     at org.json.JSONObject.getString(JSONObject.java:553)
                                                                                     at com.adyen.core.models.PaymentResponse.<init>(PaymentResponse.java:54)
                                                                                     at com.adyen.core.PaymentBroadcastReceivers$2.completionWithPaymentData(PaymentBroadcastReceivers.java:57)
                                                                                     at com.adyen.checkoutdemo.MainActivity$1$1.onSuccess(MainActivity.java:65)
                                                                                     at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:74)
                                                                                     at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:55)
                                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
                                                                                     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
                                                                                     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
                                                                                     at android.os.Handler.handleCallback(Handler.java:789)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                     at android.os.Looper.loop(Looper.java:164)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6541)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767
</pre>  After setting publicKeyToken like this:
<pre>
JSONObject jsonObject = null;
try {
jsonObject = new JSONObject(new String(response, Charset.forName("UTF-8")));
jsonObject.put("publicKeyToken", token);
} catch (JSONException e) {
 e.printStackTrace();
}
paymentDataCallback.completionWithPaymentData(jsonObject.toString().getBytes());
</pre> this problem seems to be fixed, but the payment is still unsuccessful with another error in logs:
"E/CreditCardFragment: Public key is not available; credit card payment cannot be handled",
which I can't fix, because I don't have access to the CreditCardFragment initialization.
Please help me, because it's stopper for the SDK integration

**Comment by timon-langlotz** [comment]
Hi @m-glebova,

did you generate the encryption public key for your user in the Customer Area settings?
And for using the Checkout Demo Server, did you change your API Header Key to `x-demo-server-api-key`? The demo server uses a different format for the header value.

Cheers,
Timon

**Comment by m-glebova** [comment]
Hi, 
thanks for reply. No, I didn't generate anything, just used Checkout Demo Server API Key from the settings. And yes, I used "x-demo-server-api-key" as a header. Should I press button "Generate" near the "Client Encryption Key" field? If yes, where should I use it?

**Comment by timon-langlotz** [comment]
Hi @m-glebova,

good to hear that it's solved. That was exactly what needed to happen.
No need to use it anywhere, since it's part of the response from our system, just needs to be there!

Is the demo server issue also fixed? If not, just to confirm, did you make sure to use both the header key and the secret key that are intended for the demo server?

Cheers,
Timon

**Comment by m-glebova** [comment]
Hi @timon-langlotz,
yep, I use demo server configuration and it works, thanks for reply. Just one more small question. When I run "checkoutdemo" sample project I see only one payment method - Credit Card. Maybe I missed something and additional configuration needed or it depends on some device settings? And just to confirm, you don't use attributes in themes, so if I need to change main green color, I should use Custom integration, with my own UI components?
Thanks, Marina

**Comment by timon-langlotz** [comment]
Hi @m-glebova,

first of all sorry for the long wait. The payment methods depend on the country code you provide in the setup call and your merchant account configuration. If you run into any problems there, please check with support@adyen.com on how to configure your merchant account!

Regarding theming you are correct that there is currently no way of configuring the theme colors in the quick integration. As you mentioned correctly, you would have to provide your own UI with the custom integration to change these colors. We are working on something to make the UI more configurable, but I cannot give you any timeline yet on when that will be available unfortunately.

Regards,
Timon

**Comment by m-glebova** [comment]
Hi @timon-langlotz,
thank you very much for update.
