### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getByteCount()' on a null object reference

### ISSUE THREAD

**Issue by popov-sa** [Adyen/adyen-android#1714]
**Describe the bug**
SDK version 4.10.0
Got `NullPointerException` when trying to launch payment by `saved card` using CardComponent in `Environment.TEST` (in `Environment.LIVE` everything is OK).

**To Reproduce**
Try to init CardComponent with `saved card` in `Environment.TEST`

**Expected behavior**
Crash will not occur )

**Stacktrace**
```
09:25:22.967 AndroidRuntime E
FATAL EXCEPTION: main (Ask Gemini)
Process: tv.sweet.tvplayer, PID: 27823
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getByteCount()' on a null object reference
    at com.adyen.checkout.components.api.LogoApi$cache$1.sizeOf(LogoApi.kt:67)
    at com.adyen.checkout.components.api.LogoApi$cache$1.sizeOf(LogoApi.kt:64)
    at android.util.LruCache.safeSizeOf(LruCache.java:286)
    at android.util.LruCache.put(LruCache.java:172)
    at com.adyen.checkout.components.api.LogoApi.taskFinished(LogoApi.kt:142)
    at com.adyen.checkout.components.api.LogoConnectionTask.notifyLogo$lambda-1(LogoConnectionTask.kt:63)
    at com.adyen.checkout.components.api.LogoConnectionTask.$r8$lambda$oxtl7UXK3L1XXeeEt19NzT_GjNk(Unknown Source:0)
    at com.adyen.checkout.components.api.LogoConnectionTask$$ExternalSyntheticLambda1.run(Unknown Source:4)
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:6680)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by araratthehero** [comment]
Hi @popov-sa, thank you for reporting this issue.

I am unable to reproduce the problem with the steps you provided. Could you please:
- Verify that the SDK version you use is `4.10.0`.
- Send extensive logs, which you can enable by calling `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)` in your application class and filter your logs by `CO.` to see the checkout logs only.
- Share the code where you configure the component and the part of the code where you display it.
- Provide any additional information that could help reproduce or debug the issue.
- Give a newer SDK version a try, such as `4.13.6`.

**Comment by popov-sa** [comment]
Thanks for the answer.
I can provide more detailed information next week, on Monday.
But I think the problem was with your TEST backend and not with the SDK, because in LIVE environment it works correctly. It looks like something happened to the icons on your TEST server.

**Comment by jreij** [comment]
Hi @popov-sa , do you still need help with this topic?

**Comment by popov-sa** [comment]
No, I can't reproduce the issue anymore.
Thanks
