### ISSUE TITLE
Whenever I try to open the payment component (such as a card, Prezelway, etc.) again after returning to the previous screen, the application crashes.

### ISSUE THREAD

**Issue by skamble01** [Adyen/adyen-android#1746]
Hi Team,

I have integrated AdvanceFlow for payment methods. Recently, i have moved code from activity to fragment as our requirement and after that, I am facing issue with app crash.

1. Go to the checkout page.
2. Did payment with one of payment method like card, etc.
3. Once payment is done, come back to the previous screen.
4. Again, go to the checkout page for other purchases and try to make a payment.
5. Then the app crashed and found an error as below. 

Error log:
Process: com.cex.android, PID: 2517
                 java.lang.IllegalArgumentException: SavedStateProvider with the given key is already registered
                 	at androidx.savedstate.SavedStateRegistry.registerSavedStateProvider(SavedStateRegistry.kt:110)
                 	at androidx.lifecycle.SavedStateHandleController.attachToLifecycle(SavedStateHandleController.kt:33)
                 	at androidx.lifecycle.LegacySavedStateHandleController.create(LegacySavedStateHandleController.kt:36)
                 	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:96)
                 	at androidx.lifecycle.AbstractSavedStateViewModelFactory.create(AbstractSavedStateViewModelFactory.kt:88)
                 	at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.android.kt:158)
                 	at androidx.lifecycle.viewmodel.ViewModelProviderImpl_androidKt.createViewModel(ViewModelProviderImpl.android.kt:34)
                 	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:65)
                 	at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
                 	at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:109)
                 	at com.adyen.checkout.components.core.internal.util.ViewModelExtKt.get(ViewModelExt.kt:48)
                 	at com.adyen.checkout.card.internal.provider.CardComponentProvider.get(CardComponentProvider.kt:401)
                 	at com.adyen.checkout.card.internal.provider.CardComponentProvider.get(CardComponentProvider.kt:67)
                 	at com.adyen.checkout.components.core.internal.provider.StoredPaymentComponentProvider$DefaultImpls.get(StoredPaymentComponentProvider.kt:95)
                 	at com.adyen.checkout.card.internal.provider.CardComponentProvider.get(CardComponentProvider.kt:67)
                 	at com.adyen.checkout.card.internal.provider.CardComponentProvider.get(CardComponentProvider.kt:67)
                 	at com.adyen.checkout.components.core.internal.provider.StoredPaymentComponentProvider$DefaultImpls.get$default(StoredPaymentComponentProvider.kt:87)
                 	at com.cex.android.view.fragments.buyingFlow.BuyingPaymentDetails$storedPaymentMethodUIComponent$2.invokeSuspend(BuyingPaymentDetails.kt:4112)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
                 	at android.os.Handler.handleCallback(Handler.java:938)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:201)
                 	at android.os.Looper.loop(Looper.java:288)
                 	at android.app.ActivityThread.main(ActivityThread.java:7839)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@5de22ce, Dispatchers.IO]

Note : It was working perfectly with Activity but getting error with Fragment.

Thanks in advance,
Sangram J Kamble

**Comment by skamble01** [comment]
Any update on this team?

**Comment by araratthehero** [comment]
Hi @skamble01,

From the log you shared, it looks like you're calling `StoredPaymentComponentProvider.get()` with the activity instead of the fragment instance. Please try passing the fragment and see if that resolves the issue.

I also recommend reviewing the integration to ensure all moved code is implemented correctly.

**Comment by skamble01** [comment]
Hi @araratthehero 
I have already made those adjustments, and it now functions when I open the payment components. However, if I open the card component's bottomsheet, lock my device, and then open it again, the issue occurs.
