### ISSUE TITLE
"Action type not found - REDIRECT" - when I am using IDEAL payment method

### ISSUE THREAD

**Issue by MaxKomarenski** [Adyen/adyen-android#186]
Hi, I have the following problem.
I am using Drop-In Service and when I choose the IDEAL payment method, receive a response from my server

`
{
   "method":"GET",
   "paymentData":"...",
   "paymentMethodType":"ideal",
   "type":"REDIRECT",
   "url":"https:\/\/test.adyen.com\/hpp\/redirectIdeal.shtm..."
}
`

and pass this response to CallResult

`
CallResult(
                        CallResult.ResultType.ACTION,
                        my_response
                    )
`

I get the following exception:

`
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nta.flowerapp, PID: 8785
    com.adyen.checkout.core.exception.CheckoutException: Action type not found - REDIRECT
        at com.adyen.checkout.base.model.payments.response.Action.getChildSerializer(Action.java:81)
        at com.adyen.checkout.base.model.payments.response.Action$1.deserialize(Action.java:55)
        at com.adyen.checkout.base.model.payments.response.Action$1.deserialize(Action.java:33)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleCallResult(DropInActivity.kt:288)
        at com.adyen.checkout.dropin.ui.DropInActivity$callResultReceiver$1.onReceive(DropInActivity.kt:102)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
        at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7520)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
`

It says to me that there is no "type" in my JSON but as you can see from the example of my response, it is. 
Please, help me to figure out where is the mistake.
Thanks

**Comment by caiofaustino** [comment]
Hey there,

You should pass only the JSON object inside the `action` as a result from the Drop-in service. Not the whole API response.

Can you please double check that?

**Comment by MaxKomarenski** [comment]
I have checked it and I pass only "action" JSON.
Like this ->

`
{ "method":"GET", "paymentData":"...", "paymentMethodType":"ideal", "type":"REDIRECT", "url":"https:\/\/test.adyen.com\/hpp\/redirectIdeal.shtm..." }
`

**Comment by caiofaustino** [comment]
Ahh right, sorry I misunderstood the issue. Indeed `"type":"REDIRECT"` is expected to be lower case on our side, let me check if there has been any change.

**Comment by caiofaustino** [comment]
I just double checked and the `type` comes as lower case from the API response, can you check if maybe your backend is not changing this by mistake?

**Comment by MaxKomarenski** [comment]
We have found the issue. You are using "@JsonAdaper" to adapt enum value. -> here

`
@JsonAdapter(CheckoutPaymentsAction.CheckoutActionType.Adapter.class)
    public static enum CheckoutActionType {
        AWAIT("await"),
        QRCODE("qrCode"),
        REDIRECT("redirect"),
        THREEDS2CHALLENGE("threeDS2Challenge"),
        THREEDS2FINGERPRINT("threeDS2Fingerprint"),
        VOUCHER("voucher"),
        WECHATPAYSDK("wechatpaySDK");

        private String value;

        private CheckoutActionType(String value) {
            this.value = value;
        }

        public String getValue() {
            return this.value;
        }

        public String toString() {
            return String.valueOf(this.value);
        }

   // ...

}
`



But on our backend, we are using Jackson. And Jackson does not know about that annotation because it is from gson.
In case parsing PaymentsResponse object with gson, the value goes in lower case (taken from value field of enum).
But in our case, it will not work because there no annotation for Jackson to convert enum to that value.

**Comment by caiofaustino** [comment]
Cool, glad you solved it.

Cheers.
