### ISSUE TITLE
NullPointerException When selecting credit card payment method

### ISSUE THREAD

**Issue by adriamt** [Adyen/adyen-android#188]
Hi, I'm trying to add Adyen payment using the DropIn solution.

I've added  the gradle dependency 

`implementation "com.adyen.checkout:drop-in:3.6.5"`

I get the paymentMethods from my server and I submit to the dropin where they appear but when I select CreditCard (the only payment method I have enabled) the app crash with the following error.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText android.support.design.widget.TextInputLayout.getEditText()' on a null object reference
        at com.adyen.checkout.card.CardView.initCardNumberInput(CardView.java:281)
        at com.adyen.checkout.card.CardView.initView(CardView.java:108)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:54)
        at com.adyen.checkout.card.DropInCardView.observeComponentChanges(DropInCardView.kt:53)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:58)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onViewCreated(CardComponentDialogFragment.kt:71)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I'm showing the dropin using the following code 

```
getPaymentMethods(amount) { paymentMethodsApiResponse : PaymentMethodsApiResponse? ->
            if (paymentMethodsApiResponse == null) callback.invoke(null, "Can't get payment methods")

            val cardConfiguration = CardConfiguration.Builder(activity, encryption_key).setShopperLocale(Locale.getDefault()).build()

            val amountObj = Amount()
            // Optional. In this example, the Pay button will display 10 EUR.
            amountObj.currency = "EUR"
            amountObj.value = amount

            val dropInConfiguration = DropInConfiguration.Builder(activity, resultIntent, RVAdyenPaymentGateway::class.java)
                    // Optional. Use if you want to display the amount and currency on the Pay button.
                    .setAmount(amountObj)
                    // When you're ready to accept live payments, change the value to one of our live environments.
                    .setEnvironment(Environment.TEST)
                    // Optional. Use to set the language rendered in Drop-in, overriding the default device language setting. See list of Supported languages at https://github.com/Adyen/adyen-android/tree/master/card-ui-core/src/main/res
                    // Make sure that you have set the locale in the payment method configuration object as well.
                    .setShopperLocale(Locale.getDefault())
                    .addCardConfiguration(cardConfiguration)
                    .build()
            DropIn.startPayment(activity, paymentMethodsApiResponse!!, dropInConfiguration)
        }
```

The getPaymentMethods function returns the PaymentMethodsApiResponse from my server and it works fine.

![Screenshot_20200608-172414](https://user-images.githubusercontent.com/11394100/84049722-1087e800-a9ad-11ea-9001-1f92b4554bf4.jpg)

Any clue what I'm doing wrong?

Thanks

**Comment by caiofaustino** [comment]
That's really strange. Can you maybe try to enable some logs and see if anything comes up before the error? `Logger.setLogcatLevel(Log.DEBUG)`

Or maybe make standalone project with just the minimum requirements and see if that also happens so that I can check the code more thoroughly. I can't really make out whats's going on for you since on our sample project that doesn't happen.

You can also contact [support](https://support.adyen.com/hc/en-us/requests/new?ticket_form_id=360000705420) and ask to schedule a call so we can take a look together, tell them we already talked on GitHub and you'd like to schedule something with me.

**Comment by adriamt** [comment]
I've set a Log and for the moment when the dropIn is open until the crash, these are the logs 

```
D/CO.DropInActivity: attachBaseContext
D/CO.DropInActivity: onCreate - null
D/CO.DropInViewModel: onPaymentMethodsResponseChanged
D/CO.ComponentParsingProvider: Checking availability for type - scheme
D/CO.DropInViewModel: onAvailabilityResult - scheme true
E/CO.DropInViewModel: PaymentMethod not yet supported - applepay
D/CO.ComponentParsingProvider: Checking availability for type - scheme
D/CO.DropInViewModel: onAvailabilityResult - scheme true
D/CO.ComponentParsingProvider: Checking availability for type - scheme
D/CO.DropInViewModel: onAvailabilityResult - scheme true
D/MicroMsg.PaySdk.WXFactory: createWXAPI, appId = null, checkSignature = true
D/MicroMsg.SDK.WXApiImplV10: <init>, appId = null, checkSignature = true
D/CO.DropInActivity: sendAnalyticsEvent
D/CO.PaymentMethodListDialogFragment: onCreateView
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
D/CO.PaymentMethodListDialogFragment: paymentMethods changed
V/ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@124584e[DropInActivity]
W/Choreographer: Already have a pending vsync event.  There should only be one at a time.
W/Choreographer: Already have a pending vsync event.  There should only be one at a time.
I/Surface: opservice is null false
I/Surface: opservice is null false
D/CO.PaymentMethodListDialogFragment: onPaymentMethodSelected - scheme
D/CO.DropInActivity: showComponentDialog
D/OpenGLRenderer: endAllActiveAnimators on 0x7024406200 (RippleDrawable) with handle 0x70d25cc6a0
D/DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@65f2c86[DropInActivity]
D/CO.CardComponentDialogFragment: onViewCreated
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: works.revo.loyaltyandroid, PID: 17020
    java.lang.NullPointerException: Attempt to invoke virtual method 'android.widget.EditText android.support.design.widget.TextInputLayout.getEditText()' on a null object reference
        at com.adyen.checkout.card.CardView.initCardNumberInput(CardView.java:281)
        at com.adyen.checkout.card.CardView.initView(CardView.java:108)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:54)
        at com.adyen.checkout.card.DropInCardView.observeComponentChanges(DropInCardView.kt:53)
        at com.adyen.checkout.base.ui.view.AdyenLinearLayout.attach(AdyenLinearLayout.java:58)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onViewCreated(CardComponentDialogFragment.kt:71)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1471)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1784)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1852)
        at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:802)
        at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2625)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2411)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
```

I'l try make a new project to see if it happens there too.

**Comment by adriamt** [comment]
I've just created a new project and used the dropin in the same way and it works. I'm trying to investigate what is causing this crash. I've tried to add the same libraries on both projects and still works so it's not a combination of libraries.

Any clue what it could cause that? I'll keep investigating anyway

**Comment by caiofaustino** [comment]
No sorry I can't think of what could be causing it other than maybe some XML override like I mentioned.

**Comment by adriamt** [comment]
Yes!! I found out!! As you said I have overrided a resource. I had another layout xml called `card_view` I've renamed it and it worked!!

Thanks for all your time and your help!
