### ISSUE TITLE
Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Adyen/adyen-android#215]
**Describe the bug**
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.easi.customer/com.adyen.checkout.dropin.ui.DropInActivity}: java.lang.IllegalStateException: bundle must not be null
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

Caused by java.lang.IllegalStateException: bundle must not be null
       at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(DropInActivity.java)
       at android.app.Activity.performCreate(Activity.java:8086)
       at android.app.Activity.performCreate(Activity.java:8074)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8178)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)

**Smartphone (please complete the following information):**

![image](https://user-images.githubusercontent.com/9317990/93176064-446c6980-f763-11ea-9044-276738c496ef.png)

**Additional context**
implementation "com.adyen.checkout:drop-in:3.6.6"

**Comment by ozgur00** [comment]
Hi @xiaoxiaohua333 can you share the logs by setting `com.adyen.checkout.core.log.Logger.setLogcatLevel(Log.VERBOSE)` in your application class so we can investigate the issue in detail?
