### ISSUE TITLE
Creating ActionComponents fails with ProGuard on SDK 3.7.0

### ISSUE THREAD

**Issue by zsoltvilagos** [Adyen/adyen-android#218]
**Describe the bug**

With the recommended ProGuard setup (https://github.com/Adyen/adyen-android/tree/3.7.0#proguard), the SDK 3.7.0 fails to create `com.adyen.checkout.redirect.RedirectComponent` or `com.adyen.checkout.adyen3ds2.Adyen3DS2Component`.

**To Reproduce**

1. Implement a `Fragment` to host Adyen SDK action components.
2. Use this code to add the component to the `Fragment`:
    ```
    class PaymentFragment : Fragment() {

        private lateinit var redirectComponent: RedirectComponent
        private lateinit var threeDs2Component: Adyen3DS2Component

        override fun onCreate(savedInstanceState: Bundle?) {
            super.onCreate(savedInstanceState)

            redirectComponent = RedirectComponent.PROVIDER.get(this)
            threeDs2Component = Adyen3DS2Component.PROVIDER.get(this)
        }
    }
    ```

**Expected behavior**

`RedirectComponent` and `Adyen3DS2Component` are created.

**Screenshots**

No screenshot is applicable.

**Smartphone (please complete the following information):**
 - Device: Xiaomi 9T Pro
 - OS: Android 10 Q, MIUI Global 12.0.1
 - Browser: n/a
 - Version: n/a

**Additional context**

ProGuard config:

```
## Library: Adyen ThreeDs, Redirect
-keep class com.adyen.checkout.base.model.** { *; }
-keep class com.adyen.threeds2.** { *; }
-keepclassmembers public class * implements com.adyen.checkout.base.PaymentComponent {
   public <init>(...);
}
```

Stack trace:

```
Fatal Exception: java.lang.RuntimeException: Failed to create an instance of component: class e.a.a.e.a
       at com.adyen.checkout.base.component.lifecycle.ActionComponentViewModelFactory.create(ActionComponentViewModelFactory.java:46)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:88)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:72)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:24)
       at com.example.app.ui.PaymentFragment.onCreate(Fragment.java:49)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
       at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
       at com.example.app.ui. ...
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1109)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1540)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
       at android.view.Choreographer.doFrame(Choreographer.java:722)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
Caused by java.lang.NoSuchMethodException: e.a.a.e.a.<init> [class android.app.Application, class e.a.a.e.b]
       at java.lang.Class.getConstructor0(Class.java:2332)
       at java.lang.Class.getConstructor(Class.java:1728)
       at com.adyen.checkout.base.component.lifecycle.ActionComponentViewModelFactory.create(ActionComponentViewModelFactory.java:44)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:88)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:72)
       at com.adyen.checkout.base.component.ActionComponentProviderImpl.get(ActionComponentProviderImpl.java:24)
       at com.example.app.ui.PaymentFragment.onCreate(Fragment.java:49)
       at androidx.fragment.app.Fragment.performCreate(Fragment.java:2685)
       at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1187)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
       at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2723)
       at androidx.fragment.app.FragmentStateManager.activityCreated(FragmentStateManager.java:346)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1200)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
       at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
       at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
       at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
       at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1830)
       at androidx.fragment.app.BackStackRecord.commitNow(BackStackRecord.java:297)
       at com.example.app. ... 
       at com.google.android.material.bottomsheet.BottomSheetBehavior.setStateInternal(BottomSheetBehavior.java:1109)
       at com.google.android.material.bottomsheet.BottomSheetBehavior$SettleRunnable.run(BottomSheetBehavior.java:1540)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:967)
       at android.view.Choreographer.doCallbacks(Choreographer.java:791)
       at android.view.Choreographer.doFrame(Choreographer.java:722)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:952)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

The crash comes from https://github.com/Adyen/adyen-android/compare/3.6.6...master#diff-673595324daa4c6b321a9ab52367fdcdR44

**Comment by caiofaustino** [comment]
Thanks for the detailed description.
Please also add the following rule to proguard and let me know if you still have any issues.
```
-keepclassmembers public class * implements com.adyen.checkout.base.ActionComponent {
   public <init>(...);
}
```

**Comment by zsoltvilagos** [comment]
@caiofaustino It works! Thx. Shall I maybe open a PR?

**Comment by caiofaustino** [comment]
Not yet! We are currently working on moving our workflow to GitHub where we will start accepting external PRs, but it's not quite there yet. But keep hold that idea ;)
