### ISSUE TITLE
 Failed to create 3DS2 Transaction on Android

### ISSUE THREAD

**Issue by Ehab4290** [Adyen/adyen-android#220]
**Describe the bug**
When I try to pay using one of the 3DS 2.0 test credit cards, I get component error from `Adyen3DS2Component` with this message `Failed to create 3DS2 Transaction`  

`com.adyen.checkout.core.exception.ComponentException: Failed to create 3DS2 Transaction
	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component$1.run(Adyen3DS2Component.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: com.adyen.threeds2.exception.SDKRuntimeException: Unknown directory server.
	at atd.y.c.a(Unknown Source:52)
	at atd.y.c.a(Unknown Source:48)
	at atd.x.b.a(Unknown Source:52)
	at atd.x.a.b(Unknown Source:77)
	at atd.x.a.a(Unknown Source:65)
	at atd.x.a.a(Unknown Source:56)
	at com.adyen.threeds2.internal.g.createTransaction(Unknown Source:131)
	at com.adyen.checkout.adyen3ds2.Adyen3DS2Component$1.run(Adyen3DS2Component.java:217)
	... 5 more
`

**To Reproduce**
Try to pay using 3DS 2.0 test card

**Expected behavior**
Payment should be processed successfully.

**Smartphone (please complete the following information):**
 - Device: Pixel 
 - OS: Android
 -  Adyen SDK: 3.7.0

**Comment by caiofaustino** [comment]
Hi there,

This happens with testcard `5454 5454 5454 5454` right? 
Yeah it's a known issue, thanks for pointing it out, we will make a fix in a future release.

**Comment by Ehab4290** [comment]
Yes, It happens with that test card. Thanks for clarification.
