### ISSUE TITLE
CheckoutException: Client key is not valid.

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Adyen/adyen-android#229]
**Describe the bug**
I used Drop-in(3.6.6) and Environment is Test  ,the Client Key used for network calls from the SDK to Adyen. Now Client Key is always DEFAULT_EMPTY_CLIENT_KEY =""

```
Caused by com.adyen.checkout.core.exception.CheckoutException: Client key is not valid.
       at com.adyen.checkout.base.component.BaseConfigurationBuilder.setClientKey(BaseConfigurationBuilder.java:79)
       at com.adyen.checkout.dropin.ComponentParsingProviderKt.getDefaultConfigFor(ComponentParsingProvider.kt:142)
       at com.adyen.checkout.dropin.DropInConfiguration.getConfigurationFor(DropInConfiguration.kt:103)
       at com.adyen.checkout.dropin.ActionHandler.<init>(ActionHandler.kt:39)
       at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(DropInActivity.kt:158)
       at android.app.Activity.performCreate(Activity.java:8086)
       at android.app.Activity.performCreate(Activity.java:8074)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3746)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3952)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:213)
       at android.app.ActivityThread.main(ActivityThread.java:8169)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
```

**Desktop (please complete the following information):**
 - OS: [e.g. Android]
 - Version [e.g. 28]

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 2 XL]
 - OS: [e.g. android 9]

**Additional context**
```java
        CardConfiguration.Builder cardBuilder = new CardConfiguration.Builder(this);
        cardBuilder.setShopperReference(String.valueOf(orderId));
        cardBuilder.setPublicKey('public_key');
        cardBuilder.setShopperLocale(locale);
```

**Comment by caiofaustino** [comment]
Hi there,
Client Key and Public Key are two different keys. The Client key was introduced recently to enable some future functionality but is not yet functional. You should still use the `publicKey` for now. Which seems correct from your code snippet. 

Can you make sure this code is the one that you are using? And can you confirm the format of the public key?
Should be 5 digits a pipe char(`|`) and 512 more digits, something like `12345|123456543...`

**Comment by xiaoxiaohua333** [comment]
I can't use Drop-in Test now, because  the client key is always empty. My public key is valid like (10001|AC66C15.......)

**Comment by xiaoxiaohua333** [comment]
Components:
![image](https://user-images.githubusercontent.com/9317990/95956963-a0451380-0e31-11eb-9873-e4ef1f9e8b89.png)
Drop-in:
![image](https://user-images.githubusercontent.com/9317990/95957117-e00bfb00-0e31-11eb-8966-52846f914515.png)

ClientKey is required in version 3.7.0 Drop-in?

**Comment by caiofaustino** [comment]
Sorry that Documentation is not accurate, I'll ask the docs team to change it.

Is your code the one on the first sample? This looks about right to me
```Java
 CardConfiguration.Builder cardBuilder = new CardConfiguration.Builder(this);
        cardBuilder.setShopperReference(String.valueOf(orderId));
        cardBuilder.setPublicKey("10001|AC66C15...");
        cardBuilder.setShopperLocale(locale);
```

But if you are using `cardBuilder.setClientKey()` that won't work just yet.

**Comment by xiaoxiaohua333** [comment]
IF I don't set client key,  I will get CheckoutException.
So I need try to get client key.
https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key

**Comment by caiofaustino** [comment]
And is your client key format valid? `test_123abc...`? Like I said, client and public key are different and have different formats.
Can you try not setting the client key and send me the error stacktrace?

**Comment by xiaoxiaohua333** [comment]
I check the doc，I don't know that the client key is required. so the client key is empty.

When build card configuration, I think you should use ' ||' not ' &&', so I can catch the CheckoutException.

```
    @NonNull
        public CardConfiguration build() {

            if (!CardValidationUtils.isPublicKeyValid(mBuilderPublicKey)) {
                throw new CheckoutException("Invalid Public Key. Please find the valid public key on the Customer Area.");
            }

            // This will not be triggered until the public key check above is removed as it takes prioriy.
            if (!CardValidationUtils.isPublicKeyValid(mBuilderPublicKey) && !ValidationUtils.isClientKeyValid(mBuilderClientKey)) {
                throw new CheckoutException("You need either a valid Client key or Public key to use the Card Component.");
            }

            return new CardConfiguration(
                    mBuilderShopperLocale,
                    mBuilderEnvironment,
                    mBuilderClientKey,
                    mBuilderPublicKey,
                    mBuilderHolderNameRequire,
                    mShopperReference,
                    mBuilderShowStorePaymentField,
                    mBuilderSupportedCardTypes
            );
        }
```

**Comment by caiofaustino** [comment]
We apologise for the mistake, like I said, the documentation is not accurate, and I already asked it to be changed.

Currently on version `3.7.0` you still need to pass the `publicKey`, it's just not in the constructor anymore. The `clientKey` is optional and not required.

In future versions you will have the option to choose wither:
- Just `publicKey`
- Just `clientKey`
- Both `publicKey` and `clientKey`

That's what that check on the code means, is in preparation for that as the comment states.

**Comment by xiaoxiaohua333** [comment]
Thank you @caiofaustino ~~~
