### ISSUE TITLE
java.lang.StackOverflowError: stack size 8192KB

### ISSUE THREAD

**Issue by xiaoxiaohua333** [Adyen/adyen-android#331]
**Describe the bug**
```java
Fatal Exception: java.lang.StackOverflowError: stack size 8192KB
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.runtimeError(i.java:209)
       at com.adyen.threeds2.internal.i.d(i.java:275)
       at com.adyen.threeds2.internal.i.c(i.java:256)
       at com.adyen.threeds2.internal.i.timedout(i.java:187)
       at com.adyen.threeds2.internal.f.g(f.java:391)
       at com.adyen.threeds2.internal.f.b(f.java:179)
       at com.adyen.threeds2.internal.f$a$1.run(f.java:457)
       at android.os.Handler.handleCallback(Handler.java:900)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8347)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

**Expected behavior**
From ChallengeProgressActivity

**Smartphone (please complete the following information):**
 - Device: [HUAWEI P30 Pro]
 - OS: [e.g. ANDROID 10]

**Additional context**
  implementation "com.adyen.checkout:drop-in:3.7.0"

**Comment by grandedk** [comment]
Seeing same issue

```Fatal Exception: java.lang.StackOverflowError: stack size 8MB
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.runtimeError(:209)
       at com.adyen.threeds2.internal.i.d(:275)
       at com.adyen.threeds2.internal.i.c(:256)
       at com.adyen.threeds2.internal.i.timedout(:187)
       at com.adyen.threeds2.internal.f.g(:391)
       at com.adyen.threeds2.internal.f.b(:179)
       at com.adyen.threeds2.internal.f$a$1.run(:457)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7073)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
``````

Happend after DropInActivity was mounted.

**Smartphone:**
Device: Galaxy Note8
OS: Android 9

**Additional context**
implementation "com.adyen.checkout:drop-in:3.8.2"

Happend multiple times:
01 Jul 2021, 09:06:52 - Galaxy Note8 - Android 9
22 Jun 2021, 13:49:35 - Galaxy S20 FE - Android 11

**Comment by caiofaustino** [comment]
thx for the info @grandedk, so the DropInActivity had just been initialized? Nothing related to the payment had happened yet? This is very helpful, thx a lot.

**Comment by grandedk** [comment]
Yes, as far as we can see in our systems no payment has happend yet.

**Comment by mohadian** [comment]
Hi,
We also experience the same issue in Adyen DropIn SDK

```
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.c(Unknown Source:256)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.d(Unknown Source:275)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.c(Unknown Source:256)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.d(Unknown Source:275)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.c(Unknown Source:256)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.runtimeError(Unknown Source:209)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.d(Unknown Source:275)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.c(Unknown Source:256)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.i.timedout(Unknown Source:187)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.f.g(Unknown Source:391)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.f.b(Unknown Source:179)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.adyen.threeds2.internal.f$a$1.run(Unknown Source:457)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:907)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:216)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7625)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
10-01 12:06:32.511 28900 28900 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

Smartphone:
Device: HUAWEI P20 lite
OS: Android 9

Additional context
implementation "com.adyen.checkout:drop-in:3.8.3"

Happened multiple times
The Drop-in is opened successfully, then the user is navigated to the 3DS page, when the user is returning to the App (hence DropIn SDK), the app crashes with the `Fatal Exception: java.lang.StackOverflowError`

**Comment by sanoopv3** [comment]
Any **solution** for this?? .. we are **stuck** in this stage...!!

**Comment by caiofaustino** [comment]
Thx, we found an issue and will release the fix in the next version of the 3DS2 SDK since this issue is not coming directly from the Checkout SDK. You can follow up [here](https://github.com/Adyen/adyen-3ds2-android/issues/42)
