### ISSUE TITLE
Missing proguard rules for com.adyen.checkout?

### ISSUE THREAD

**Issue by Nailer** [Adyen/adyen-android#367]
Hi!  I'm using your android components in a flutter plugin that wraps functionality we need on both iOS and Android. 

The last couple of days I have been debugging an issue where calls like `RedirectComponent.PROVIDER.get(activity, null)` would fail due to tree-shaking performed by R8/proguard.

I would get an exception like this:
```
E/flutter ( 2305): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: PlatformException(error, Failed to create an instance of component: class c.a.a.f.a, null, java.lang.RuntimeException: Failed to create an instance of component: class c.a.a.f.a
E/flutter ( 2305): 	at com.adyen.checkout.base.component.lifecycle.b.a(Unknown Source:54)
E/flutter ( 2305): 	at androidx.lifecycle.v.a(Unknown Source:26)
E/flutter ( 2305): 	at androidx.lifecycle.v.a(Unknown Source:23)
E/flutter ( 2305): 	at c.a.a.b.g.a.a(Unknown Source:17)
E/flutter ( 2305): 	at c.a.a.b.g.a.a(Unknown Source:0)
E/flutter ( 2305): 	at c.c.a.g.a(Unknown Source:10)
E/flutter ( 2305): 	at c.c.a.g.a(Unknown Source:124)
E/flutter ( 2305): 	at c.c.a.m.onMethodCall(Unknown Source:70)
E/flutter ( 2305): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/flutter ( 2305): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:57)
E/flutter ( 2305): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/flutter ( 2305): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 2305): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter ( 2305): 	at android.os.Looper.loop(Looper.java:183)
E/flutter ( 2305): 	at android.app.ActivityThread.main(ActivityThread.java:7660)
E/flutter ( 2305): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 2305): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/flutter ( 2305): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

After a lot of head scratching I managed to get things to work by adding the following rule to my project's proguard-rules.pro
`-keep class com.adyen.checkout.**  { *; }`

I haven't tried your library directly from a native android app, so I don't know if this is some weird side effect of it being embedded in a flutter project. 

I do feel, however, that when using dynamic constructor calls, like you're doing, you should probably strive to make it more fool proof? :)

**Comment by caiofaustino** [comment]
Hi there, have you already tried the rules we have in our readme session?
https://github.com/Adyen/adyen-android#proguard

**Comment by jreij** [comment]
No custom Proguard rules are needed anymore, since `4.6.0`.
