### ISSUE TITLE
[2.4.12] NullPointerException in PaymentMethodUtil

### ISSUE THREAD

**Issue by alexisloiselle** [Adyen/adyen-android#391]
Hi, I'm taking a chance here since we don't use the latest version of the sdk.

We have an exception thrown in the `PaymentMethodUtil` file which causes crashes in our react-native app.

Here's the stacktrace:
```
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.adyen.checkout.ui.internal.common.util.PaymentMethodUtil.a(PaymentMethodUtil.java:2)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.q(CardDetailsActivity.java:14)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.o(CardDetailsActivity.java:6)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.updatePayButtonState(CardDetailsActivity.java:10)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.a(CardDetailsActivity.java:3)
       at com.adyen.checkout.ui.internal.common.activity.CheckoutSessionActivity.onAuthenticationDetailsRequired(CheckoutSessionActivity.java:132)
       at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java)
       at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:4)
       at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:21)
       at com.adyen.checkout.core.internal.BaseManager.access$200(BaseManager.java)
       at com.adyen.checkout.core.internal.BaseManager$ActivityScopedHandler.onActive(BaseManager.java:14)
       at com.adyen.checkout.core.internal.lifecycle.LifecycleFragment.onResume(LifecycleFragment.java:30)
       at android.app.Fragment.performResume(Fragment.java:2568)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1341)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1576)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1637)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManagerImpl.java:3050)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:3012)
       at android.app.FragmentController.dispatchResume(FragmentController.java:205)
       at android.app.Activity.performResume(Activity.java:7594)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4006)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4046)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
```

This stacktrace is obfuscated, but the latest function calls are 

```
       at com.adyen.checkout.ui.internal.common.util.PaymentMethodUtil.getRequirementForInputDetail(PaymentMethodUtil.java:2)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.getHolderNameValidationResult(CardDetailsActivity.java:14)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.isValidCardDetails(CardDetailsActivity.java:6)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.updatePayButtonState(CardDetailsActivity.java:10)
```
~~Not 100% sure about `getHolderNameValidationResult`, could also be `getPhoneNumberValidationResult`.~~ Confirmed

I was unfortunately not able to reproduce the issue. But it seems to be related to a `resume` event.

Happens on many devices
- Samsung Galaxy (S8, S9, A50 ...)
- Xperia XA2
- OnePlus Nord
- ...

Android versions:
- 9, 10 and 11

Is there a fix for that kind of issue? I know the obvious solution is probably to update the sdk, but, as I said, I'm taking a chance because it would mean quite a lot of work to update the sdk to the latest version for our team.

Thanks!

**Comment by caiofaustino** [comment]
Hey there, yeah sorry this seems tricky to solve, this version is pretty much deprecated at this point.
Do you have any information on how often that happens? I don't have any knowledge on React Native, I assume it wouldn't interfere with the lifecycle here but just wondering if anything could be related, because I assume more merchants would also face this issue and I haven't heard anything similar so far.

**Comment by alexisloiselle** [comment]
It's very rare that we see this kind of event; less than 1%. Usually, there are no problems with the lifecycle when using react-native. Anyways, feel free to close this issue if nothing obvious comes to mind. Thanks for taking the time!
