### ISSUE TITLE
Ability to close DropInActivity

### ISSUE THREAD

**Issue by jesperjohansson** [Adyen/adyen-android#393]
**Is your feature request related to a problem? Please describe.**
We are building a React Native bridge for v4 and have some difficulties controlling the Android drop-in. We would preferably be able to access all methods in DropInActivity but we're not sure how, if possible. 

**Describe the solution you'd like**
Not sure this is the right approach or if there is another, better way. But maybe make DropInActivity listen to additional intents so we can trigger `terminate()` from outside. 

**Describe alternatives you've considered**
Right now we are using this which kind of works but it results in an error:
```kotlin
fun close() {
  Log.d(TAG, "Close was called")
  reactContext.currentActivity?.finishActivity(DropIn.DROP_IN_REQUEST_CODE)
}
```

```
D/AdyenDropInViewManager: Handle response - Refused
    handleFinishWithError
D/CO.DropInServiceKt: dispatching DropInServiceResult
D/AdyenDropInViewManager: Close was called
D/CO.DropInActivityKt: handleDropInServiceResult - Error
    handleDropInServiceResult ERROR - reason: null
    showError - message: Error sending payment. Please try again.
D/AdyenDropInViewManager: onActivityResult - data: com.example.reactnativeadyendropin.MainActivity@d95edfarequestCode: 529resultCode: 0data: (null)
D/EGL_emulation: eglMakeCurrent: 0xe7305ae0: ver 3 0 (tinfo 0xe7303cf0)
D/EGL_emulation: eglMakeCurrent: 0xe7305ae0: ver 3 0 (tinfo 0xe7303cf0)
D/EGL_emulation: eglMakeCurrent: 0xe7305ae0: ver 3 0 (tinfo 0xe7303cf0)
D/CO.DropInServiceKt: unbindService - DropInActivity
D/CO.Adyen3DS2Component: onCleared
E/WindowManager: android.view.WindowLeaked: Activity com.adyen.checkout.dropin.ui.DropInActivity has leaked window DecorView@475c784[DropInActivity] that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:511)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:346)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at android.app.Dialog.show(Dialog.java:329)
        at androidx.appcompat.app.AlertDialog$Builder.show(AlertDialog.java:1009)
        at com.adyen.checkout.dropin.ui.DropInActivity.showError(DropInActivity.kt:308)
        at com.adyen.checkout.dropin.ui.DropInActivity.handleDropInServiceResult(DropInActivity.kt:422)
        at com.adyen.checkout.dropin.ui.DropInActivity.access$handleDropInServiceResult(DropInActivity.kt:76)
        at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1.onChanged(DropInActivity.kt:112)
        at com.adyen.checkout.dropin.ui.DropInActivity$serviceConnection$1$onServiceConnected$1.onChanged(DropInActivity.kt:106)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:131)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:149)
        at androidx.lifecycle.LiveData.setValue(LiveData.java:307)
        at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
        at androidx.lifecycle.LiveData$1.run(LiveData.java:91)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
D/CO.DropInServiceKt: onUnbind
D/CO.DropInServiceKt: onDestroy
I/ReactNativeJS: 'handleError', { resultCode: 'Refused' }
I/ReactNativeJS: 'Show error', { resultCode: 'Refused' }
D/EGL_emulation: eglMakeCurrent: 0xe7305ae0: ver 3 0 (tinfo 0xe7303cf0)

```

**Additional context**
We want to be able to handle as much as possible in the JS part. Right now we are making the requests (with the data from the drop-in) in the JS part and then we pass the response back to the drop-in. But we also want to be able to handle error messages and request failures so we need to close the drop-in before showing our own error. 

Version 4.0.0-beta02 (com.adyen.checkout:drop-in:4.0.0-beta02)

**Comment by jreij** [comment]
Hi, thanks for reaching out. You can return a `DropInServiceResult.Error` in the `makePaymentsCall` or `makeDetailsCall` methods, inside your implementation of `DropInService` and set the `dismissDropIn` parameter to `true`, which would properly finish the `DropInActivity`.
You can handle this dismissal in `onActivityResult` inside the activity or fragment that launched the drop-in. You can pass the activity result to the `DropIn.handleActivityResult` method to wrap the result inside a `DropInResult` object.
You can also set the `errorMessage` and `reason` parameters in the `DropInServiceResult.Error`, and you will receive them back in `onActivityResult`.
Let me know if this works for you.

**Comment by jesperjohansson** [comment]
@jreij Thanks! It works but there is the issue that an error alert is shown. Is there a way to close the drop-in without showing the error alert? Tried with `DropInServiceResult.Error(null, null, true)`
![image](https://user-images.githubusercontent.com/21033162/118662973-b6b0b480-b7f0-11eb-9675-af8f2a6a945d.png)

**Comment by jreij** [comment]
@jesperjohansson hmm actually I don't think this is doable with `DropInServiceResult.Error`. 
How about sending `DropInServiceResult.Finished` with a specific value for the `result` param (`"closed"` for example) which would indicate that the drop in finished but it wasn't actually successful.
However, I think this solution would only work if you do not provide a `resultHandlerIntent` to `DropIn.startPayment`, otherwise `DropInServiceResult.Finished` will trigger this intent indeed and you'll have to handle the result in the newly launched activity.

**Comment by jesperjohansson** [comment]
@jreij Thank you, `DropInServiceResult.Finished("closed")` did the trick! 🎉
