### ISSUE TITLE
Crash on Adyen SDK 2.4.12 (ErrorDialogFragment.java)

### ISSUE THREAD

**Issue by larakitb** [Adyen/adyen-android#408]
Hi!

This issue is impacting a considerable amount of our user base.
Unfortunately, we couldn't reproduce this crash.

Here's the stacktrace that we're getting from Crashlytics:

![Screen Shot 2021-06-08 at 11 19 00 PM](https://user-images.githubusercontent.com/69874236/121287632-eb73d100-c8af-11eb-8094-1891596e4bc8.png)

![Screen Shot 2021-06-08 at 11 23 23 PM](https://user-images.githubusercontent.com/69874236/121287939-87054180-c8b0-11eb-82b8-93684f69ade0.png)

`Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:11)
       at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:26)
       at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:70)
       at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:1)
       at androidx.fragment.app.DialogFragment.show(DialogFragment.java:13)
       at com.adyen.checkout.ui.internal.common.fragment.ErrorDialogFragment.showIfNotShown(ErrorDialogFragment.java:8)
       at com.adyen.checkout.ui.internal.common.activity.CheckoutSessionActivity$7.onFailure(CheckoutSessionActivity.java:21)
       at com.adyen.checkout.threeds.Card3DS2Authenticator$ListenerDelegate.protocolError(Card3DS2Authenticator.java:40)
       at com.adyen.threeds2.internal.i.protocolError(i.java:9)
       at com.adyen.threeds2.internal.f.a(f.java:6)
       at com.adyen.threeds2.internal.f$2.a(f.java:38)
       at com.adyen.threeds2.internal.f$2.accept(f.java:2)
       at com.adyen.threeds2.internal.f.a(f.java:2)
       at com.adyen.threeds2.internal.f.a(f.java:7)
       at com.adyen.threeds2.internal.f.b(f.java:39)
       at com.adyen.threeds2.internal.f.a(f.java)
       at com.adyen.threeds2.internal.f.a(f.java:2)
       at atd.a.d$1.run(d.java:8)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

If this version of SDK is still supported, could someone please have a look, Thank you.

**Comment by caiofaustino** [comment]
We just release version `2.4.13` which should be available soon which has a fix/mitigation attempt for this issue.
