### ISSUE TITLE
Crash on Adyen SDK 2.4.12 (PaymentMethodUtil.java)

### ISSUE THREAD

**Issue by larakitb** [Adyen/adyen-android#409]
Hi!

This issue is impacting a considerable amount of our user base.
Unfortunately, we couldn't reproduce this crash.

Here's the stacktrace that we're getting from Crashlytics:

![Screen Shot 2021-06-08 at 11 24 57 PM](https://user-images.githubusercontent.com/69874236/121288064-c2077500-c8b0-11eb-8e15-708ed42a71aa.png)

![Screen Shot 2021-06-08 at 11 25 17 PM](https://user-images.githubusercontent.com/69874236/121288082-cb90dd00-c8b0-11eb-8d2d-8608d4a1f703.png)

`Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
       at com.adyen.checkout.ui.internal.common.util.PaymentMethodUtil.getRequirementForInputDetail(PaymentMethodUtil.java:2)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.getHolderNameValidationResult(CardDetailsActivity.java:14)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.isValidCardDetails(CardDetailsActivity.java:6)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.updatePayButtonState(CardDetailsActivity.java:10)
       at com.adyen.checkout.ui.internal.card.CardDetailsActivity.handleCheckoutException(CardDetailsActivity.java:3)
       at com.adyen.checkout.ui.internal.common.activity.CheckoutSessionActivity.onAuthenticationDetailsRequired(CheckoutSessionActivity.java:132)
       at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java)
       at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:4)
       at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:21)
       at com.adyen.checkout.core.internal.BaseManager.access$200(BaseManager.java)
       at com.adyen.checkout.core.internal.BaseManager$ActivityScopedHandler.onActive(BaseManager.java:14)
       at com.adyen.checkout.core.internal.lifecycle.LifecycleFragment.onResume(LifecycleFragment.java:30)
       at android.app.Fragment.performResume(Fragment.java:2580)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1346)
       at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1581)
       at android.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1642)
       at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManagerImpl.java:3052)
       at android.app.FragmentManagerImpl.dispatchResume(FragmentManagerImpl.java:3014)
       at android.app.FragmentController.dispatchResume(FragmentController.java:206)
       at android.app.Activity.performResume(Activity.java:8133)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4647)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4690)
       at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2267)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:8167)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)`

If this version of SDK is still supported, could someone please have a look, Thank you.

**Comment by caiofaustino** [comment]
We just release version `2.4.13` which should be available soon which has a fix/mitigation attempt for this issue.
