### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#457]
Hello,

The App crash when click payment button. The exception is: _**Stored payment method is empty or not found**_.

 com.adyen.checkout.core.exception.ComponentException: Stored payment method is empty or not found.
        at com.adyen.checkout.dropin.ui.stored.PreselectedStoredPaymentMethodFragment.onCreateView(PreselectedStoredPaymentMethodFragment.kt:89)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2699)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:320)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1199)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1368)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1446)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1509)
        at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:447)
        at androidx.fragment.app.FragmentManager.executeOps(FragmentManager.java:2181)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2004)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1959)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1861)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2641)
        at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2589)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:247)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:541)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at com.adyen.checkout.dropin.ui.DropInActivity.onStart(DropInActivity.kt:244)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1432)
        at android.app.Activity.performStart(Activity.java:7848)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by caiofaustino** [comment]
Hi, this was recently fixed in #472 and will be available in the next release.

**Comment by N1ghtly** [comment]
> Hi, this was recently fixed in #472 and will be available in the next release.

Thanks for the update. Do you have a timeline for next release?

**Comment by N1ghtly** [comment]
@caiofaustino Any update? Our team is blocked on this atm :/

**Comment by caiofaustino** [comment]
No sorry we don't have an ETA on the release yet, but I thought I had shared a temporary fix  you can make on your end.
You can manually remove the items from the list before initializing the Drop-in, something like this
`paymentMethodsApiResponse.storedPaymentMethods = paymentMethodsApiResponse.storedPaymentMethods?.filter { it.isEcommerce }`

**Comment by jreij** [comment]
@xanderdeseyn hi, we just released 4.2.0 which includes the fix for this issue, it should be live in maven central a bit 🙂
