### ISSUE TITLE
App crashes for Spanish language

### ISSUE THREAD

**Issue by hackaprende** [Adyen/adyen-android#461]
**Describe the bug**
When I set my phone language in Spanish and try to run my app with versions 4.0.0 and 4.1.0, it crashes and shows this error:
`    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example/com.rnlib.adyen.ui.AdyenComponentActivity}: java.util.IllformedLocaleException: Ill-formed language: español [at index 0]`

**To Reproduce**
1. Set your phone in Spanish language
2. Try to open the card form

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Huawei p9
 - OS: Android

**Comment by ozgur00** [comment]
Hey @hackaprende! Can you share the full stacktrace for more detailed investigation of the issue? Also please mention the OS version as well.

**Comment by hackaprende** [comment]
@ozgur00 That's the full stacktrace. I can reproduce it consistently:
```
2021-09-28 15:39:48.278 2007-6053/? E/DollieActivityManagerAdapter: HwActivityNotifierEx null uid
2021-09-28 15:39:48.289 1452-1489/? E/system_server: Invalid ID 0x00000000.
2021-09-28 15:39:48.311 1452-2004/? E/ProcessInfoCollector: getProcessInfo: failed to find this proc 
2021-09-28 15:39:48.348 27663-27663/? E/com.example: Unknown bits set in runtime_flags: 0x8000
2021-09-28 15:39:48.371 27663-27663/? E/libc: Access denied finding property "runtime.mmitest.isrunning"
2021-09-28 15:39:48.375 627-627/? E/WifiHAL: enter wifi_get_link_stats
2021-09-28 15:39:48.387 1452-1651/? E/WificondControl: Noise: 0, Snr: 0, Chload: -1
2021-09-28 15:39:48.388 1452-1489/? E/WindowManager: icon is null!!
2021-09-28 15:39:48.390 2189-3124/? E/AwareLog: SPKSchedFeature: Uid has been sent, ignore.
2021-09-28 15:39:48.391 1452-1489/? E/WindowManager: icon is null!!
2021-09-28 15:39:48.410 1793-2005/? E/HSC_SEC_BG: AiProtectionUtils:AI is not supported, current platform is:kirin710
2021-09-28 15:39:48.458 834-883/? E/AwareLog: iawared: GetFileContent open /proc/27693/task/27696/cpuset fail errno(2)!
2021-09-28 15:39:48.479 27663-27699/com.example E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@c79aaaa
2021-09-28 15:39:48.488 27663-27663/com.example E/SoLoader: couldn't find DSO to load: libjscexecutor.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.example/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64
     result: 0
2021-09-28 15:39:48.529 450-450/? E/SELinux: avc:  denied  { find } for interface=vendor.huawei.hardware.sensors::ISensors sid=u:r:untrusted_app:s0:c136,c257,c512,c768 pid=27663 scontext=u:r:untrusted_app:s0:c136,c257,c512,c768 tcontext=u:object_r:default_hisi_hwservice:s0 tclass=hwservice_manager permissive=0
2021-09-28 15:39:48.546 27663-27706/com.example E/SoLoader: couldn't find DSO to load: libfbjni.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.example/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64
     result: 0
2021-09-28 15:39:48.549 27663-27707/com.example E/AndroidRuntime: FATAL EXCEPTION: FlipperConnectionThread
    Process: com.example, PID: 27663
    java.lang.NoClassDefFoundError: <clinit> failed for class com.facebook.flipper.android.EventBase; see exception in other thread
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
2021-09-28 15:39:48.549 27663-27706/com.example E/AndroidRuntime: FATAL EXCEPTION: FlipperEventBaseThread
    Process: com.example, PID: 27663
    java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libfbjni.so
    	SoSource 0: com.facebook.soloader.ApkSoSource[root = /data/data/com.example/lib-main flags = 1]
    	SoSource 1: com.facebook.soloader.DirectorySoSource[root = /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64 flags = 0]
    	SoSource 2: com.facebook.soloader.DirectorySoSource[root = /vendor/lib64 flags = 2]
    	SoSource 3: com.facebook.soloader.DirectorySoSource[root = /system/lib64 flags = 2]
    	Native lib dir: /data/app/com.example-rn57iHVtteGnFDsL5ugv4A==/lib/arm64
     result: 0
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:896)
        at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:725)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:649)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:629)
        at com.facebook.soloader.NativeLoaderToSoLoaderDelegate.loadLibrary(NativeLoaderToSoLoaderDelegate.java:29)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:51)
        at com.facebook.soloader.nativeloader.NativeLoader.loadLibrary(NativeLoader.java:30)
        at com.facebook.jni.HybridData.<clinit>(HybridData.java:34)
        at com.facebook.flipper.android.FlipperThread.run(FlipperThread.java:25)
2021-09-28 15:39:48.558 2189-3124/? E/AwareLog: SPKSchedFeature: Uid has been sent, ignore.
2021-09-28 15:39:48.562 1452-4554/? E/HwActivityTaskManagerServiceEx: invalid ActivityRecord, error.
2021-09-28 15:39:48.562 1452-4554/? E/HwActivityTaskManagerServiceEx: parse activity info error.
2021-09-28 15:39:48.565 848-3121/? E/iMonitor: FaultDetect: DumptoolPrintf return.
2021-09-28 15:39:48.565 848-3122/? E/iMonitor: FaultDetect: FaultEngineTracePrintf return.
```

**Comment by ozgur00** [comment]
Hi @hackaprende! I don't see the `IllformedLocaleException` you mentioned in the first message in the stacktrace. Can you check again and share the stacktrace for the `IllformedLocaleException`? Also please provide the OS version you're using and whether if you're using Drop In or standalone Card Component?

**Comment by hackaprende** [comment]
Hi @ozgur00, The error was in the react native Adyen payment library which we are using as a bridge, sorry for the troubles.
