### ISSUE TITLE
java.util.IllformedLocaleException: Ill-formed language: undefined [at index 0]

### ISSUE THREAD

**Issue by chornomor** [Adyen/adyen-android#514]
I have a language related crash. 
Unfortunately I have no steps to reproduce, I just have a stacktrace on the crashlytics.

The library version is 3.7.2, perhaps this crash was fixed in the latest version. 
I will update the library. But I don't want to wait for new failures.
So if anyone knows of a fix, please let me know and I will close this issue.

Device
Brand:samsung
Model:Galaxy S6
Orientation: Portrait
RAM free: 602.41 MB
Disk free: 4.06 GB

Operating System
Version:7.0
Orientation: Portrait
Rooted:No

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.driivz.gronn/com.adyen.checkout.dropin.ui.DropInActivity}: java.util.IllformedLocaleException: Ill-formed language: undefined [at index 0]
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

Caused by java.util.IllformedLocaleException: Ill-formed language: undefined [at index 0]
at java.util.Locale$Builder.setLanguage(Locale.java:2411)
at com.adyen.checkout.core.util.LocaleUtil.fromLanguageTag(LocaleUtil.java:81)
at com.adyen.checkout.dropin.ui.DropInActivity.createLocalizedContext(DropInActivity.java:176)
at com.adyen.checkout.dropin.ui.DropInActivity.attachBaseContext(DropInActivity.java:128)
at android.app.Activity.attach(Activity.java:6878)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2861)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
at android.app.ActivityThread.-wrap14(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6682)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by rahulsainani** [comment]
Also facing the same issue in production on many huawwi and samsung devices, stack trace below, seems to be caused by creating locale on line 82 on `LocaleUtil.java`: `Locale.Builder().setLanguage(language[0]).setRegion(language[1]).build();`

```
Caused by java.util.IllformedLocaleException: Ill-formed region: HANS [at index 0]
       at java.util.Locale$Builder.setRegion(Locale.java:2976)
       at com.adyen.checkout.core.util.LocaleUtil.fromLanguageTag(LocaleUtil.java:82)
       at com.adyen.checkout.dropin.ui.DropInActivity.createLocalizedContext(DropInActivity.java:188)
       at com.adyen.checkout.dropin.ui.DropInActivity.attachBaseContext(DropInActivity.java:135)
       at android.app.Activity.attach(Activity.java:8017)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3847)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4081)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2462)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:219)
       at android.app.ActivityThread.main(ActivityThread.java:8393)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
```

Would there be an update with a fix?

**Comment by jreij** [comment]
Hi thanks for reaching out!

I can see from the stack traces that the language value in the locale used by @chornomor seems `null`, which for @rahulsainani I can see that the region is `HANS` which is not a valid region. I wonder how did you guys get these values.

Are you calling `DropInConfiguration.Builder.setShopperLocale` at any stage? If so, how are you creating the `Locale` and what values are you passing to it?

**Comment by rahulsainani** [comment]
HI @jreij Thanks for the quick response. Yes we are setting the locale and I think the issue is on our side of how we are constructing the locale, will confirm and share more as we gather more info. Apologies for flagging it too soon! 

Not entirely related to this, while debugging this issue, wondered if it would be possible to pass in out own instance of Logger, if sdk could provide an interface Logger, so we can debug these and other issues that occur in production by checking the internal sdk logs as well that we will send to our tracking libs. Could create an issue for this if you think this is a reasonable feature request?

**Comment by jreij** [comment]
@rahulsainani no worries! We are working on an improvement that would ensure this issue fails earlier (before starting drop-in) and with a more meaningful error message. But ultimately this still should be solved on your side, if it is indeed the Locale issue that I suspect.

As for the logger, that's a very interesting idea. We do not have the option at the moment, but I will raise this suggestion internally and get back to you with a decision 🙂

**Comment by chornomor** [comment]
@jreij thank you for help. I think I can close the issue.

**Comment by jreij** [comment]
@chornomor can you confirm if it was indeed a Locale issue from your side? It would help us handle it better in the future 🙂
