### ISSUE TITLE
Crash at CardComponent creation with adyen 4.3.0

### ISSUE THREAD

**Issue by plastiv** [Adyen/adyen-android#536]
**Describe the bug**
After upgrading adyen sdk library from 4.2.0 to 4.3.0 the crash is happening when creating CardComponent. On the first look seems to be connected with `We rely on SavedStateHandle in all components ` change.

**To Reproduce**

1. We are creating `CardComponent` with dagger

```
    // in fragment
    @Inject
    lateinit var cardComponent: CardComponent
    
    // in dagger module
    @FragmentScope
    @Provides
    fun provideAdyenCardComponent(
        fragment: AdyenCreditCardInputFragment,
        paymentMethod: PaymentMethod,
        cardConfiguration: CardConfiguration
    ): CardComponent {
        return CardComponent.PROVIDER.get(fragment, paymentMethod, cardConfiguration)
    }
```
2. I think dagger injects at `onAttach` which seems to be an issue according to the crash error message

```
    Process: de.flixbus.app.debug, PID: 3939
    java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
        at androidx.savedstate.SavedStateRegistry.a(SavedStateRegistry.java:77)
        at androidx.lifecycle.SavedStateHandleController.j(SavedStateHandleController.java:67)
        at androidx.lifecycle.a.c(AbstractSavedStateViewModelFactory.java:67)
        at androidx.lifecycle.j0.b(ViewModelProvider.java:185)
        at androidx.lifecycle.j0.a(ViewModelProvider.java:150)
        at s2.c.b(CardComponentProvider.kt:59)
        at s2.c.c(CardComponentProvider.kt:32)
        at s2.c.d(CardComponentProvider.kt:26)
        at d00.d.a(AdyenCreditCardInputFragmentModule.kt:42)
        at d00.e.a(AdyenCreditCardInputFragmentModule_ProvideAdyenCardComponentFactory.java:57)
        at sj.k1$a0.e(DaggerAppComponent.java:10404)
        at sj.k1$a0.c(Unknown Source:0)
        at sj.k1$a0$a.get(DaggerAppComponent.java:10455)
        at sh.b.get(DoubleCheck.java:47)
        at sj.k1$a0.i(DaggerAppComponent.java:10427)
        at sj.k1$a0.h(DaggerAppComponent.java:10418)
        at sj.k1$a0.a(DaggerAppComponent.java:10370)
        at dagger.android.DispatchingAndroidInjector.c(DispatchingAndroidInjector.java:113)
        at dagger.android.DispatchingAndroidInjector.a(DispatchingAndroidInjector.java:134)
        at rh.a.c(AndroidSupportInjection.java:75)
        at rh.a.b(AndroidSupportInjection.java:67)
        at gn.c.onAttach(BaseFragment.kt:21)
        at d00.c.onAttach(AdyenCreditCardInputFragment.kt:72)
        at androidx.fragment.app.Fragment.performAttach(Fragment.java:2922)
        at androidx.fragment.app.r.c(FragmentStateManager.java:464)
        at androidx.fragment.app.r.m(FragmentStateManager.java:275)
        at androidx.fragment.app.FragmentManager.c0(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.e1(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.Z(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager.R(FragmentManager.java:3138)
        at androidx.fragment.app.FragmentManager.x(FragmentManager.java:3072)
        at androidx.fragment.app.g.c(FragmentController.java:251)
        at androidx.fragment.app.d.onStart(FragmentActivity.java:502)
        at androidx.appcompat.app.d.onStart(AppCompatActivity.java:246)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
        at android.app.Activity.performStart(Activity.java:8076)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3660)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Expected behavior**

Kinda should work as before adyen 4.3.0

**Additional context**

I'm not sure what SavedStateHandle brings to the table. Does it work with dagger(-android)? Workarounds possible?

Some guidance is needed. It is also okay if you just verify that crash is not related to some other adyen internal changes we would probably have to figure out how to integrate google libs with other googles work on our side. Opening an issue for visibility for others.

**Comment by jreij** [comment]
Hi @plastiv, thanks for reaching out! I believe the component should work with Dagger but you need to take into consideration that our components are view models, so I guess it has to be injected after `onCreate`. Are you accounting for that already?

This is not a recent change, components were already view models but I think the latest changes triggered the crash. We added `SavedStateHandle` in 4.3.0 in order to manage the internal state of the component without needing additional interaction from your side.
