### ISSUE TITLE
Upgrade from 4.2.0 to 4.3.0

### ISSUE THREAD

**Issue by badredaha** [Adyen/adyen-android#547]
**Describe the bug**
When I upgraded the version from 4.2 to 4.3 the app crash with stak:

```
FATAL EXCEPTION: main
Process: com.louvrehotels.app.dev, PID: 13253
android.view.InflateException: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
Caused by: android.view.InflateException: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
```

**Comment by ozgur00** [comment]
Hi @badredaha! Thanks for reaching out to us. Can you share the full stack trace of the exception for us to make a more detailed investigation?

**Comment by badredaha** [comment]
Hi @ozgur00 

FYI : I use DropIn not Component inetration 

** Log **
FATAL EXCEPTION: main

Caused by: java.lang.reflect.InvocationTargetException

FATAL EXCEPTION: main
Process: com.louvrehotels.app.dev, PID: 10391
android.view.InflateException: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
Caused by: android.view.InflateException: Binary XML file line #67 in com.louvrehotels.app.dev:layout/fragment_card_component: Error inflating class com.adyen.checkout.card.CardView
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
	at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: android.view.InflateException: Binary XML file line #181 in com.louvrehotels.app.dev:layout/card_view: Binary XML file line #181 in com.louvrehotels.app.dev:layout/card_view: Error inflating class <unknown>
Caused by: android.view.InflateException: Binary XML file line #181 in com.louvrehotels.app.dev:layout/card_view: Error inflating class <unknown>
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:654)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
	at com.adyen.checkout.card.databinding.CardViewBinding.inflate(CardViewBinding.java:164)
	at com.adyen.checkout.card.CardView.<init>(CardView.kt:54)
	at com.adyen.checkout.card.CardView.<init>(CardView.kt:43)
	at com.adyen.checkout.card.CardView.<init>(Unknown Source:11)
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at android.view.LayoutInflater.createView(LayoutInflater.java:852)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1004)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1121)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1124)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1082)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:680)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
	at com.adyen.checkout.dropin.databinding.FragmentCardComponentBinding.inflate(FragmentCardComponentBinding.java:65)
	at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreateView(CardComponentDialogFragment.kt:43)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
	at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
	at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:223)
	at android.app.ActivityThread.main(ActivityThread.java:7656)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).
	at com.google.android.material.internal.ThemeEnforcement.checkTheme(ThemeEnforcement.java:243)
	at com.google.android.material.internal.ThemeEnforcement.checkMaterialTheme(ThemeEnforcement.java:217)
	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(ThemeEnforcement.java:145)
	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(ThemeEnforcement.java:115)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:469)
	at com.google.android.material.textfield.TextInputLayout.<init>(TextInputLayout.java:428)
	... 43 more

**Comment by jreij** [comment]
@badredaha does the problem go away if you only revert back to `4.2.0`?

**Comment by badredaha** [comment]
@jreij 

Yes! no problem with 4.3.0.

**Comment by jreij** [comment]
Can you provide us your final merged manifest when using the version that produces the crash?

**Comment by badredaha** [comment]
I will close this. thanks Team
