### ISSUE TITLE
Android equivalent for iOS SDK string "adyen.confirmPreauthorization"

### ISSUE THREAD

**Issue by xanderdeseyn** [Adyen/adyen-android#549]
The iOS SDK of Adyen detects when we are storing a payment method through a payment of 0 cents. It will then show the "Pre-authorise" button instead of the regular "Pay" button. It seems this functionality is not supported in the Android SDK?

Am I missing something or is there a workaround perhaps?

**Comment by jreij** [comment]
Thanks for reaching out. The same can be done in Android by not setting an Amount when launching drop-in (do not call `DropInConfiguration.Builder.setAmount`.

**Comment by xanderdeseyn** [comment]
It seems to be using the general "pay_button" string, is that correct?

**Comment by jreij** [comment]
Yep exactly! `pay_button` when no amount is specified, `pay_button_with_value` with an amount.

**Comment by xanderdeseyn** [comment]
Great, thanks for the swift responses!

**Comment by xanderdeseyn** [comment]
Re-opening this because we are having issues by not setting an amount. Once there is one stored payment method, the dropin crashes if we do not set an amount:

```(Console Logs) 07-12 15:38:37.924  D/OOMEventManagerFK(21508): checkEventAndDumpForJE: 0
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at java.lang.reflect.Method.invoke(Native Method)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.ActivityThread.main(ActivityThread.java:7564)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.os.Looper.loop(Looper.java:225)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.os.Handler.dispatchMessage(Handler.java:107)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3334)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.Activity.performStart(Activity.java:7946)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.adyen.checkout.dropin.ui.DropInActivity.onStart(DropInActivity.kt:244)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.adyen.checkout.dropin.ui.stored.PreselectedStoredPaymentMethodFragment.onViewCreated(PreselectedStoredPaymentMethodFragment.kt:116)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.adyen.checkout.components.util.CurrencyUtils.formatAmount(CurrencyUtils.java:39)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.adyen.checkout.components.util.CheckoutCurrency.find(CheckoutCurrency.java:193)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): 	at com.adyen.checkout.components.util.CurrencyUtils.assertCurrency(CurrencyUtils.java:53)
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): com.adyen.checkout.core.exception.CheckoutException: Currency NONE not supported
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): Process: com.themobilecompany.delijn, PID: 21508
(Console Logs) 07-12 15:38:37.902  E/AndroidRuntime(21508): FATAL EXCEPTION: main```

**Comment by jreij** [comment]
hi @xanderdeseyn, are you calling `CardConfiguration.Builder.setHideCvcStoredCard(true)`? Can you explain your use case a bit? I can see that you want to make a payment of 0 cents, does that apply to new cards only, or also stored cards? And do you need to skip asking for a CVC for stored cards?

**Comment by xanderdeseyn** [comment]
It's a "mock" payment to store a payment method, so showing stored cards is not actually necessary in this flow. I am indeed calling that function, is there a problem with that? We need to skip CVC for stored cards, yes.

**Comment by jreij** [comment]
So in that specific case (zero-value auth) you user should only be allowed to pay with a new card, and them selecting a stored card might cause you an issue, or at least it shouldn't happen, is that correct?

If so then I suggest you remove the `storedPaymentMethods` from the `PaymentMethodsApiResponse` parameter when calling `DropIn.startPayment` and only keep the methods you want your users to be able to make a 0 value payment with.

In all cases this is a bug from our side and we'll fix it in later releases but the use case to reproduce this bug doesn't seem like a valid scenario, or at least not for you 🙂

**Comment by xanderdeseyn** [comment]
True, we'll handle it like that. Thanks!
