### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles

### ISSUE THREAD

**Issue by christianfindsen** [Adyen/adyen-android#581]
**Describe the bug**

We are seeing some crashes with:
_Fatal Exception: java.lang.IllegalArgumentException
Cannot add the same observer with different lifecycles_

The crash is happening on the QrCodeComponent when starting to observe for some users.

I am only starting to observe once, called in a function that gets called after onViewCreated and using the Fragment's getViewLifecycleOwner() as lifecycleOwner.

Same function is also starting an observe on the redirectComponent no crash there.

**To Reproduce**
Not been able to reproduce

**Expected behavior**
Not crashing ;)

**Additional context**
Fatal Exception: java.lang.IllegalArgumentException: Cannot add the same observer with different lifecycles
       at androidx.lifecycle.LiveData.observe(LiveData.java:199)
       at com.adyen.checkout.qrcode.QRCodeComponent.observe(QRCodeComponent.kt:107)
       at com.app.tgtg.activities.checkout.fragments.EmbeddedPaymentFragment.setupRedirect(EmbeddedPaymentFragment.kt:773)
       at com.app.tgtg.activities.checkout.fragments.EmbeddedPaymentFragment.onViewCreated(EmbeddedPaymentFragment.kt:255)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:2987)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:546)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
       at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
       at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
       at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3138)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3072)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:251)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:502)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:201)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
       at android.app.Activity.performStart(Activity.java:7348)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3138)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:180)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:165)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:142)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7050)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by ozgur00** [comment]
Hi @christianfindsen! Thanks for sharing the details of the issue! Are you using `QRCodeComponent` as a standalone component, or as part of Drop-in? Also can you share which version you're using?

**Comment by christianfindsen** [comment]
I'm using the QRCodeComponent as a standalone component version 4.4.0

**Comment by christianfindsen** [comment]
@ozgur00 Any update on this?

**Comment by jreij** [comment]
Hi @christianfindsen, this error message is coming from inside the `LiveData` class. We have a `LiveData` inside every component, when you call `QRCodeComponent.observe` you technically just observe this live data. From the stack trace it seems like there's something wrong happening with your observer.

Can you share some code on how you are observing the component and where?

**Comment by christianfindsen** [comment]
I am observing it on my fragments `OnViewCreated`. I did try and remove the observer before adding it but did no change.

**Comment by jreij** [comment]
Hi @christianfindsen, were you able to solve this issue or not yet?

**Comment by christianfindsen** [comment]
Yes, I moved the observe start to when I handle an Action instead of starting it when the view gets created.
