### ISSUE TITLE
"Don' t keep activities"  is active and reopen the app while the Credit Card bottom sheet input is open results in a crash

### ISSUE THREAD

**Issue by BenedictP** [Adyen/adyen-android#595]
**Describe the bug**
Check the dev setting "Don't keep activities" and close and reopen the app while the Credit Card bottom sheet input is open resulting in a crash:
```
2022-02-23 13:56:50.783 14390-14390/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adyen.checkout.example, PID: 14390
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.adyen.checkout.example/com.adyen.checkout.dropin.ui.DropInActivity}: java.lang.RuntimeException: Cannot create an instance of class com.adyen.checkout.dropin.ui.viewmodel.DropInViewModel
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3685)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
     Caused by: java.lang.RuntimeException: Cannot create an instance of class com.adyen.checkout.dropin.ui.viewmodel.DropInViewModel
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:221)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278)
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54)
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41)
        at com.adyen.checkout.dropin.ui.base.DropInBottomSheetDialogFragment.getDropInViewModel(DropInBottomSheetDialogFragment.kt:37)
        at com.adyen.checkout.dropin.ui.base.BaseComponentDialogFragment.onCreate(BaseComponentDialogFragment.kt:102)
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreate(CardComponentDialogFragment.kt:58)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276)
        at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(DropInActivity.kt:160)
        at android.app.Activity.performCreate(Activity.java:8054)
        at android.app.Activity.performCreate(Activity.java:8034)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
     Caused by: java.lang.InstantiationException: java.lang.Class<com.adyen.checkout.dropin.ui.viewmodel.DropInViewModel> has no zero argument constructor
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create(ViewModelProvider.java:278) 
        at androidx.lifecycle.SavedStateViewModelFactory.create(SavedStateViewModelFactory.java:112) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:185) 
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:54) 
        at androidx.lifecycle.ViewModelLazy.getValue(ViewModelProvider.kt:41) 
        at com.adyen.checkout.dropin.ui.base.DropInBottomSheetDialogFragment.getDropInViewModel(DropInBottomSheetDialogFragment.kt:37) 
        at com.adyen.checkout.dropin.ui.base.BaseComponentDialogFragment.onCreate(BaseComponentDialogFragment.kt:102) 
        at com.adyen.checkout.dropin.ui.component.CardComponentDialogFragment.onCreate(CardComponentDialogFragment.kt:58) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949) 
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475) 
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278) 
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3128) 
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:3061) 
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:240) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:276) 
        at com.adyen.checkout.dropin.ui.DropInActivity.onCreate(DropInActivity.kt:160) 
        at android.app.Activity.performCreate(Activity.java:8054) 
        at android.app.Activity.performCreate(Activity.java:8034) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3666) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3842) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7842) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**To Reproduce**
1. Go to Dev settings
2. Check "Don't keep activities"
2. Open the example app
3. Click "Start Checkout"
4. Click "Credit Card"
5. Move the app to the background
6. Try to open the app again from the background
7. Crash

**Expected behavior**
It shouldn't crash.

**Screenshots**

https://user-images.githubusercontent.com/5817002/155326668-8dcee98e-2a21-449b-8b11-de1160dd9001.mp4

**Smartphone (please complete the following information):**
I saw 2 crashes in production (but we just started a new release):
- Samsung A10
- OPPO A5 2020

**Additional context**

**Comment by ozgur00** [comment]
Hi @BenedictP! Thanks for bringing the issue to our attention in detail, we'll investigate it!

**Comment by BenedictP** [comment]
This is now our #1 crash with 31 affected users in the last 7 days ❗  😞
