### ISSUE TITLE
In-app quick integration - generationtime error

### ISSUE THREAD

**Issue by rodrigueslg** [Adyen/adyen-android#6]
I'm following the In-app quick integration documentation for Android and I am receiving the error:

Provided payment data response is invalid
org.json.JSONException: No value for generationtime
	at org.json.JSONObject.get(JSONObject.java:389)
	at org.json.JSONObject.getString(JSONObject.java:550)
	at com.adyen.core.models.PaymentResponse.<init>(PaymentResponse.java:49)
	at com.adyen.core.PaymentBroadcastReceivers$2.completionWithPaymentData(PaymentBroadcastReceivers.java:57)
	at md510efd7a204942edddcf434380b3266f7.DroisAdyenService.n_onSuccess(Native Method)
	at md510efd7a204942edddcf434380b3266f7.DroisAdyenService.onSuccess(DroisAdyenService.java:65)
	at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:74)
	at com.adyen.core.utils.AsyncHttpClient$1.onNext(AsyncHttpClient.java:55)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:200)
	at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:252)
	at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:109)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7229)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
onStateChanged: ABORTED
Payment aborted.

I am using the Demo Server.

**Comment by timon-langlotz** [comment]
Hi @rodrigueslg,

it looks like the response you are forwarding with `PaymentDataCallback.completionWithPaymentData(byte[] paymentData)` does not have the correct contents. Could you set a breakpoint where you call this method and check the contents of the data? You can call `new String(paymentData)` to see the contents in JSON format.

Kind regards,
Timon

**Comment by AbhiHearty** [comment]
Hi @timon-langlotz  I have Tried the same and after printing the same new String(paymentData) i gpt a message like  "errorMessage" : "Response was not 200, instead got 403", I have Used the Sdk data as it is without any change

I am using the Demo Server.

Thanks in Advance,
Abhi

**Comment by timon-langlotz** [comment]
Could you post the data you are sending in the setup call? Then we can investigate further!

Cheers
Timon

**Comment by AbhiHearty** [comment]
@timon-langlotz  yes i will post it for you .. 

    private String getSetupDataString(final String token) {
        final JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("merchantAccount", "TestMerchant"); 
            jsonObject.put("shopperLocale", "NL");
            jsonObject.put("token", token);
            jsonObject.put("returnUrl", "example-shopping-app://");
            jsonObject.put("countryCode", "NL");
            final JSONObject amount = new JSONObject();
            amount.put("value", "17408");
            amount.put("currency", "USD");
            jsonObject.put("amount", amount);
            jsonObject.put("channel", "android");
            jsonObject.put("reference", "M+M Black dress & accessories");
            jsonObject.put("shopperReference", "example-customer@exampleprovider");
        } catch (final JSONException jsonException) {
            Log.e(TAG, "Setup failed", jsonException);
        }
        return jsonObject.toString();
    }

This is it same as the SDK

**Comment by timon-langlotz** [comment]
Hi @AbhiHearty,

you need to use your own merchant account that is mapped to your API key.
That's the reason why you are getting a 403.

Let us know if this worked!
Cheers,
Timon

**Comment by AbhiHearty** [comment]
I dint see any merchant account details in my dashboard . Can you tell me the steps to get that so that i can check . Note : Am in test mode not live .

**Comment by timon-langlotz** [comment]
Hi @AbhiHearty,

could you please send an email to support@adyen.com?
They'll provide you with detailed steps.

Thanks,
Timon

**Comment by AbhiHearty** [comment]
Hi @timon-langlotz  yes am using the my merchant account only but same issue exists ..

Merchant Account Taken from Accounts tab

**Comment by timon-langlotz** [comment]
Hi @AbhiHearty,

I would recommend to contact support@adyen.com then in any case, since it sounds like this is out of my control. But please let us know when your issue is resolved!

Cheers,
Timon

**Comment by AbhiHearty** [comment]
@timon-langlotz , 

Okay ll be back soon with the updated status.

Cheers,
Abhi
