### ISSUE TITLE
App-module & CustomUiApplication-module: Pressing pay button crashes app.

### ISSUE THREAD

**Issue by RikNorakomi** [Adyen/adyen-android#8]
Values for merchantServerUrl, merchantApiSecretKey & merchantApiHeaderKeyForApiSecretKey are set.

Wehn running app and pressing pay button app crashes:

  // Add the URL for your server here; or you can use the demo server of Adyen: 
https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/
    private String merchantServerUrl = "https://checkoutshopper-test.adyen.com/checkoutshopper/demoserver/";

    // Add the api secret key for your server here; you can retrieve this key from customer area.
    private String merchantApiSecretKey = "0101578***etc***DCB5588C48224C6007";

    // Add the header key for merchant server api secret key here; e.g. "x-demo-server-api-key"
    private String merchantApiHeaderKeyForApiSecretKey = "x-demo-server-api-key";

Logcat output:
com.adyen.customuiapplication V/PaymentDataEntryFragment: buildPaymentRequest()
09-29 09:28:58.375 25978-25978/com.adyen.customuiapplication E/art: ClassLinker::FindClass not found:Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
09-29 09:28:58.378 25978-25978/com.adyen.customuiapplication E/art: ClassLinker::FindClass not found:Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
09-29 09:28:58.385 25978-25978/com.adyen.customuiapplication E/art: ClassLinker::FindClass not found:Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
09-29 09:28:58.387 25978-25978/com.adyen.customuiapplication D/AndroidRuntime: Shutting down VM
09-29 09:28:58.388 25978-25978/com.adyen.customuiapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.adyen.customuiapplication, PID: 25978
                                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lorg/jacoco/agent/rt/internal_b0d6a23/Offline;
                                                                                   at com.adyen.core.utils.AmountUtil.$jacocoInit(AmountUtil.java:0)
                                                                                   at com.adyen.core.utils.AmountUtil.<clinit>(AmountUtil.java)
                                                                                   at com.adyen.core.utils.AmountUtil.parseMajorAmount(AmountUtil.java:0)
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment.buildPaymentRequest(PaymentDataEntryFragment.java:77)
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment.access$200(PaymentDataEntryFragment.java:22)
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment$1.onClick(PaymentDataEntryFragment.java:58)
                                                                                   at android.view.View.performClick(View.java:4848)
                                                                                   at android.view.View$PerformClick.run(View.java:20300)
                                                                                   at android.os.Handler.handleCallback(Handler.java:815)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                   at android.os.Looper.loop(Looper.java:194)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5690)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                                                Caused by: java.lang.ClassNotFoundException: Didn't find class "org.jacoco.agent.rt.internal_b0d6a23.Offline" on path: DexPathList[[zip file "/data/app/com.adyen.customuiapplication-1/base.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.adyen.customuiapplication-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]
                                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                                   at com.adyen.core.utils.AmountUtil.$jacocoInit(AmountUtil.java:0) 
                                                                                   at com.adyen.core.utils.AmountUtil.<clinit>(AmountUtil.java) 
                                                                                   at com.adyen.core.utils.AmountUtil.parseMajorAmount(AmountUtil.java:0) 
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment.buildPaymentRequest(PaymentDataEntryFragment.java:77) 
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment.access$200(PaymentDataEntryFragment.java:22) 
                                                                                   at com.adyen.customuiapplication.PaymentDataEntryFragment$1.onClick(PaymentDataEntryFragment.java:58) 
                                                                                   at android.view.View.performClick(View.java:4848) 
                                                                                   at android.view.View$PerformClick.run(View.java:20300) 
                                                                                   at android.os.Handler.handleCallback(Handler.java:815) 
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:104) 
                                                                                   at android.os.Looper.loop(Looper.java:194) 
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5690) 
                                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                                               	Suppressed: java.lang.ClassNotFoundException: org.jacoco.agent.rt.internal_b0d6a23.Offline
                                                                                   at java.lang.Class.classForName(Native Method)
                                                                                   at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                                                   at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                                                   		... 17 more
                                                                                Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by RikNorakomi** [comment]
Disabling instant run seemed to do the trick :)

**Comment by timon-langlotz** [comment]
Hi @RikNorakomi ,

thanks for contacting us! Unfortunately, Instant Run and JaCoCo don't work together very well. Glad that you could resolve the issue by disabling Instant Run. 

You can find more information about limitations of Instant Run with third-party plugins here: https://developer.android.com/studio/run/index.html#ir-limitations

Kind regards,
Timon
