### ISSUE TITLE
Crashes after upgrading Adyen SDK in release build

### ISSUE THREAD

**Issue by przan** [Adyen/adyen-android#82]
After upgrading the SDK to version 2.4.5 and adding `com.adyen.checkout.threeds` I get crashes for release builds with following stack trace:

```
java.lang.RuntimeException: Class c does not declare constructor with arguments [class org.json.JSONObject].
	at com.adyen.checkout.base.internal.Objects.reflectiveInit(Objects.java:47)
	at com.adyen.checkout.base.internal.JsonObject.parseFrom(JsonObject.java:45)
	at com.adyen.checkout.base.internal.JsonDecodable.decodeFrom(JsonDecodable.java:27)
	at com.adyen.checkout.base.internal.Base64Coder.decode(Base64Coder.java:32)
	at com.adyen.checkout.base.internal.Base64Coder.decode(Base64Coder.java:27)
	at com.adyen.checkout.threeds.Card3DS2Authenticator.createFingerprint(Card3DS2Authenticator.java:81)
	at com.adyen.checkout.ui.internal.card.CardDetailsActivity.onAuthenticationDetailsRequired(CardDetailsActivity.java:346)
	at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:24)
	at com.adyen.checkout.core.internal.AuthenticationManager.dispatch(AuthenticationManager.java:16)
	at com.adyen.checkout.core.internal.BaseManager.checkDispatch(BaseManager.java:46)
	at com.adyen.checkout.core.internal.BaseManager.setData(BaseManager.java:37)
	at com.adyen.checkout.core.internal.PaymentHandlerImpl$8.run(PaymentHandlerImpl.java:464)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5910)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1405)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1200)
Caused by: java.lang.NoSuchMethodException: <init> [class org.json.JSONObject]
	at java.lang.Class.getConstructor(Class.java:531)
	at java.lang.Class.getDeclaredConstructor(Class.java:510)
	at com.adyen.checkout.base.internal.Objects.reflectiveInit(Objects.java:37)
	... 19 more
```

Card used: 5212 3456 7890 1242

`build.gradle`
```
    implementation "com.adyen.checkout:ui:2.4.5"
    implementation "com.adyen.checkout:nfc:2.4.5"
    implementation "com.adyen.checkout:threeds:2.4.5"
```

ProGuard:
```
-keep class com.adyen.checkout.core.** { *; }
-dontwarn com.adyen.checkout.nfc.**
-dontwarn com.adyen.checkout.googlepay.**
-dontwarn com.adyen.checkout.wechatpay.**
-dontwarn com.adyen.checkout.threeds.**
```

**Comment by przan** [comment]
@caiofaustino Hi, it happened 5/5 times for release build (with ProGuard) for the card 5212 3456 7890 1242. There was no crash when there was no obfuscation.

**Comment by caiofaustino** [comment]
Can you send me the obfuscation artifacts on the ticked so that I can deobfuscate the stacktrace?

**Comment by przan** [comment]
@caiofaustino I've edited the first post and added deobfuscated logs. I've just reproduced the issue so it looks like `always` for an app with proguard with following configuration:
```
-keep class com.adyen.checkout.core.** { *; }
-dontwarn com.adyen.checkout.nfc.**
-dontwarn com.adyen.checkout.googlepay.**
-dontwarn com.adyen.checkout.wechatpay.**
-dontwarn com.adyen.checkout.threeds.**
```

**Comment by caiofaustino** [comment]
Please add this line to your proguard configuration and let me know if that fixes it.
`-keep class com.adyen.checkout.threeds.internal.model.** { *; }`

**Comment by przan** [comment]
Yep, adding this line prevents the crashes. Thanks!
