### ISSUE TITLE
InvalidInputException: acsSignedContent could not be verified

### ISSUE THREAD

**Issue by kaserdan** [Adyen/adyen-android#86]
Hi, I am using 
com.adyen.checkout:core:2.4.5
com.adyen.checkout:core-card:2.4.5

Everything was fine, but suddenly I keep getting 
```
com.adyen.threeds2.exception.InvalidInputException: acsSignedContent could not be verified.
     at com.adyen.threeds2.internal.l.doChallenge(:34).
```
while calling `Card3DS2Authenticator#presenetChannelge`

Cause:
```
Caused by: java.security.cert.CertificateException: Error verifying certificate chain: EMAILADDRESS=support@adyen.com, CN=3DS2 Simulator VISA DS Certificate Authority, OU=Checkout, O=Adyen N.V., L=Amsterdam, ST=Noord-Holland, C=NL
     at com.adyen.threeds2.internal.h.e.i.a(:20)
     at com.adyen.threeds2.internal.h.d.d.a(:14)
     at com.adyen.threeds2.internal.l.doChallenge(:9)
 	... 13 more
 Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:153)
     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
     at com.adyen.threeds2.internal.h.e.i.a(:18)
 	... 15 more
```
Am I doing something wrong?

**Comment by kaserdan** [comment]
Evething works with com.adyen.threeds:adyen-3ds2:2.1.0-rc02
