### ISSUE TITLE
NPE when ChallengeActivity is being paused during handling new Intent

### ISSUE THREAD

**Issue by michal-chojnacki** [Adyen/adyen-android#934]
**Describe the bug**
Our app crashes from time to time on NPE on ChallengeActivity. From logs it looks like `ChallengeActivity` has been just paused and `saveInstanceState` was called for `DropInActivity`. I've tried to reproduce it, unfortunately unsuccessfully but maybe you'll able to find something or give some advice how to fix the problem.

We're using "com.adyen.checkout:drop-in:4.8.0"

Here is full stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setAlpha(float)' on a null object reference
    at android.view.View$3.setValue(View.java:27007)
    at android.view.View$3.setValue(View.java:27004)
    at android.animation.PropertyValuesHolder$FloatPropertyValuesHolder.setAnimatedValue(PropertyValuesHolder.java:1379)
    at android.animation.ObjectAnimator.animateValue(ObjectAnimator.java:990)
    at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:684)
    at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:647)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1079)
    at android.animation.ValueAnimator.start(ValueAnimator.java:1098)
    at android.animation.ObjectAnimator.start(ObjectAnimator.java:852)
    at android.animation.ValueAnimator.startWithoutPulsing(ValueAnimator.java:1091)
    at android.animation.AnimatorSet.handleAnimationEvents(AnimatorSet.java:1149)
    at android.animation.AnimatorSet.startAnimation(AnimatorSet.java:1234)
    at android.animation.AnimatorSet.start(AnimatorSet.java:729)
    at android.animation.AnimatorSet.start(AnimatorSet.java:684)
    at com.adyen.threeds2.internal.ui.activity.a.a
    at com.adyen.threeds2.internal.ui.activity.a.a
    at com.adyen.threeds2.internal.ui.activity.a.c
    at com.adyen.threeds2.internal.ui.activity.a.b
    at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.a
    at com.adyen.threeds2.internal.ui.activity.ChallengeActivity.onNewIntent
    at android.app.Activity.performNewIntent(Activity.java:7831)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1428)
    at android.app.Instrumentation.callActivityOnNewIntent(Instrumentation.java:1441)
    at android.app.ActivityThread.deliverNewIntents(ActivityThread.java:3687)
    at android.app.ActivityThread.handleNewIntent(ActivityThread.java:3699)
    at android.app.servertransaction.NewIntentItem.execute(NewIntentItem.java:53)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
    at android.os.Handler.dispatchMessage(Handler.java:107)
    at android.os.Looper.loop(Looper.java:241)
    at android.app.ActivityThread.main(ActivityThread.java:7617)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by OscarSpruit** [comment]
Hi, thank you for raising this issue! We have seen this issue before https://github.com/Adyen/adyen-3ds2-android/issues/39. Could it be that some overlay is trying to interact with the ChallengeActivity in your app as stated in the issue? 

In the mean time we are looking into what else could cause this.

**Comment by michal-chojnacki** [comment]
We don't have anything what is adding an overlay in our app. The only interaction is that we're executing `Protocol.terminateDropIn` when we're navigating user from checkout screen to no show him Adyen drop-in on other screens.

**Comment by michal-chojnacki** [comment]
When user moves app to the background with opened Adyen drop-in and the comes back to foreground drop-in will be still opened what is ok. However during that time we can detect that user completed order for example on other platform (for example he prefers to make payment on the web). In that case we're navigating user from the checkout and we need to close adyen drop-in to prevent him trying making payment again.

**Comment by OscarSpruit** [comment]
Interesting use case, thanks for explaining! Still I advise to not use `Protocol.terminateDropIn` for this. The recommended way of doing this is by adding the method below to your `DropInService` implementation and calling it instead of `Protocol.terminateDropIn`.
```Kotlin
fun finishDropIn() {
    sendResult(DropInServiceResult.Finished(MANUALLY_DISMISSED))
}
```
This will make `DropInActivity` finish with `Activity.RESULT_OK` as result and `DropIn.RESULT_KEY to MANUALLY_DISMISSED` in the intent extras.

We will have a look if we can reproduce it with that extra information.

**Comment by jreij** [comment]
Hi again @michal-chojnacki , were you able to resolve this issue or get help for it anywhere else?

**Comment by jreij** [comment]
Closing for inactivity, please reopen if you still need help with this.
