### ISSUE TITLE
Crash when navigating back after removing stored payment method

### ISSUE THREAD

**Issue by jonekdahl** [Adyen/adyen-android#947]
**Describe the bug**
We're implementing removal of stored payment methods in our app so I have been looking at how the example app in this repo does it. When playing with the example app, I found a possible crash bug that occurs when you navigate back after removing a stored payment method.

Stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.adyen.checkout.example, PID: 14140
    com.adyen.checkout.core.exception.ComponentException: Stored payment method is empty or not found.
        at com.adyen.checkout.dropin.ui.stored.PreselectedStoredPaymentMethodFragment.onCreateView(PreselectedStoredPaymentMethodFragment.kt:95)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.DialogFragment.performCreateView(DialogFragment.java:489)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**To Reproduce**
1. Run the example app
1. Click on START CHECKOUT
1. Select Credit Card
1. Enter card details and enable "Save for my next payment"
1. Click the Pay button
1. Click on START CHECKOUT again
1. Long click the stored card and click the trash can icon on the right
1. Click YES, REMOVE in the confirmation dialog
1. In the PAYMENT METHODS selection, press the back button 

**Expected behavior**
The drop-in component should be closed, like it normally is when navigating back from the payment methods selection.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 - Device: Google Pixel 5 (emulator)
 - OS: API 31
 - Browser: N/A
 - Version: 4.9.0 (adyen-android)

**Additional context**
Since we're using the 4.9.0 version of adyen-android, that's the tag I checked out when I tested the example app.

**Comment by etman55** [comment]
Thank you for reaching out, but I have been following you steps and everything works fine can you please maybe take a small video of the steps?

**Comment by jonekdahl** [comment]
@etman55 Were you able to reproduce the bug?

**Comment by etman55** [comment]
Yup, we're working on it and will fix it ASAP

**Comment by etman55** [comment]
For the moment we fixed this crash, this will roll out in the next release 4.9.1.
